Updating module to allow for tmt import of 'metadata' file for #1002
teemtee/tmt pull request #1043
Opened 2022-02-09 12:19 UTC by pfdaly

Module has been updated to allow for tmt to import 'metadata' file as well as 'Makefile'. If both exist in the directory, priority is given to 'metadata' file.

The command remains the same, 'tmt test import --makefile' to allow for backwards compatibility.

# Existing code behaviour.
# Makefile, Purpose file, and main.fmf present in the directory.

[root@pdaly parent]# tmt test import --makefile
Checking the '/root/auto-kernel/tmt_fork/tmt/tests/test/import/data/parent' directory.
Makefile found in '/root/auto-kernel/tmt_fork/tmt/tests/test/import/data/parent/Makefile'.
task: /tmt/smoke
summary: Simple smoke test
test: ./runtest.sh
framework: shell
contact: James Bond <007@MI6.com>
component: tmt
duration: 5m
environment:
{'AVC_ERROR': '+no_avc_check',
 'CONTEXT': 'distro=fedora',
 'TEST': 'one two three'}
require: tmt
recommend: fmf
tag: multihost
relates: https://bugzilla.redhat.com/show_bug.cgi?id=1234567
relates: https://bugzilla.redhat.com/show_bug.cgi?id=9876543
Purpose found in '/root/auto-kernel/tmt_fork/tmt/tests/test/import/data/parent/PURPOSE'.
description:
Just run 'tmt --help' to make sure the binary is sane.
This is really that simple. Nothing more here. Really.
Nitrate Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638944): Ticket expired
[root@pdaly parent]#

# Implemented code behaviour
# Makefile, Purpose file, and main.fmf present in the directory.

[root@pdaly parent]# tmt test import --makefile
Checking the '/root/auto-kernel/tmt_fork/tmt/tests/test/import/data/parent' directory.
Makefile found in '/root/auto-kernel/tmt_fork/tmt/tests/test/import/data/parent/Makefile'.
task: /tmt/smoke
summary: Simple smoke test
test: ./runtest.sh
framework: shell
contact: James Bond <007@MI6.com>
component: tmt
duration: 5m
environment:
{'AVC_ERROR': '+no_avc_check',
 'CONTEXT': 'distro=fedora',
 'TEST': 'one two three'}
require: tmt
recommend: fmf
tag: multihost
relates: https://bugzilla.redhat.com/show_bug.cgi?id=1234567
relates: https://bugzilla.redhat.com/show_bug.cgi?id=9876543
relates: https://bugzilla.redhat.com/show_bug.cgi?id=2222222
Purpose found in '/root/auto-kernel/tmt_fork/tmt/tests/test/import/data/parent/PURPOSE'.
description:
Just run 'tmt --help' to make sure the binary is sane.
This is really that simple. Nothing more here. Really.
Nitrate Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638944): Ticket expired
[root@pdaly parent]#

# metadata, Purpose file, and main.fmf present in the directory.

[root@pdaly parent]# tmt test import --makefile
Checking the '/root/auto-kernel/tmt_fork/tmt/tests/test/import/data/parent' directory.
metadata found in '/root/auto-kernel/tmt_fork/tmt/tests/test/import/data/parent/metadata'.
task: /tmt/smoke
summary: Simple smoke test
test: ./runtest.sh
framework: shell
contact: Napoleon Solo <TheManFrom@UNCLE.com>
component: tmt
duration: 5m
recommend: fmf tmt
Purpose found in '/root/auto-kernel/tmt_fork/tmt/tests/test/import/data/parent/PURPOSE'.
description:
Just run 'tmt --help' to make sure the binary is sane.
This is really that simple. Nothing more here. Really.
Nitrate Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638944): Ticket expired
[root@pdaly parent]#

2022-02-11 14:49 UTC, psss commented
Thank you for looking into this! Would you mind adding at least a basic test coverage for the new feature? It would help with the review to have example data for experimenting. You could extend the existing test [/tests/test/import](https://github.com/psss/tmt/tree/master/tests/test/import) or write a new test.

Regarding the options, currently we have an enable/disable option for each metadata source:

```
  --nitrate / --no-nitrate    Import test metadata from Nitrate
  --purpose / --no-purpose    Migrate description from PURPOSE file
  --makefile / --no-makefile  Convert Beaker Makefile metadata
```

I think it would be good to introduce similar options for the `restraint` metadata parsing as well. @lukaszachy, @thrix, what do you think?

2022-02-11 14:56 UTC, lukaszachy commented
Should be `--restraint / --no-restraint  Convert restraint metadata file`

Now what should be the default and how fatal would be missing piece ... 
IMO from user PoV `tmt test import .` should just work. However If there is explicit --restraint on the commandline I'd expect failure if 'metadata' file is missing. But that could be part of another PR.

2022-03-03 11:26 UTC, lukaszachy requested changes
Hi @pfdaly, thanks for the PR. I believe the logic for `repoRequires` is wrong and `softDependencies` are missing.
Makefile maps Requires -> recommend, RhtsRequire -> require
and metadata should do repoRequires -> require, softDependencies -> recommend

So that makes `regex_requires` technically a recommend/softDependencies.
IMO the `regex_XXX` names should called after target destination - so singular form.
This way later one will use regex_require to fill data['require'] and regex_recommend to fill data['recommend']

2022-03-03 17:59 UTC, pfdaly commented
Hi @lukaszachy,
My latest push fixes the variable names of the regex patterns to match the key names of the data dictionary.

The change also includes the mapping of the metadata repoRequires > require & softDependencies -> recommend.

2022-03-08 10:09 UTC, lukaszachy requested changes
Thank you, few comments which I didn't see before.
Also test.sh is mixing tabs and spaces -> rest of the file is with spaces so please retab ;)

Hopefully nitpick - commit header is used in release notes so please set to something shorter https://tmt.readthedocs.io/en/stable/contribute.html#commits

IMO among the lines of "Allow import from restraint's metadata file"

2022-03-08 10:10 UTC, lukaszachy commented
Also please do rebase to the latest main. It might fix the tests.

2022-03-08 10:37 UTC, lukaszachy commented on tests/test/import/test.sh
> +        rlRun "mv $tmp/data/parent/child/metadata $tmp/data/parent/child/.metadata" 0 "Removing restraint metadata file in tmp directory"
There is rlFileBackup & rlFileRestore in beakerlib. So you might call `rlFileBackp <path>`, then `rm <path>` and in the end just call `rlFileRestore` to restore all backuped files.

2022-03-15 17:25 UTC, lukaszachy commented on tmt/convert.py
> +        data['component'] = 'tmt'
Please do not set this value if it cannot be determined properly. Once can set it in top main.fmf to have it available in all children nodes. Value 'tmt' is not a correct one.

2022-03-16 13:51 UTC, lukaszachy approved these changes
Thank you very much for the PR, I'll rebase and merge.

2022-03-16 16:44 UTC, lukaszachy commented
So, hopefully I fixed pre-commit format issue and tests now pass

2022-03-16 18:09 UTC, merged

2022-03-16 19:30 UTC, pfdaly commented
Great, thanks for that @lukaszachy.
It's odd that the pre-commit failed with a pep8 error as I'd executed Pycodestyle on it with a pass result prior to pushing. There must be some detection differences between the two.

2022-03-17 09:31 UTC, lukaszachy commented
@pfdaly Maybe - I found out that even different versions of checker might provide different opinions about code format.
Best is to set up  [pre-commit](https://tmt.readthedocs.io/en/stable/contribute.html#develop) which should be the same locally and in PR

2022-03-17 16:49 UTC, BeeGrech commented
Please forgive my question if covered - I dont see where metadata dependencies are processed.

2022-03-17 17:01 UTC, lukaszachy commented
Ah, now I see it in https://restraint.readthedocs.io/en/latest/tasks.html#dependencies
So `dependencies` are addition to `repoRequires` ?

2022-03-17 17:10 UTC, BeeGrech commented
repoRequires is actually like a preparation script-
[](https://restraint.readthedocs.io/en/latest/tasks.html?highlight=reporequires#reporequires)repoRequires
A semicolon-delimited (;) list of additional tasks needed for this task to run.

now another question, I dont think tests support prepare steps...