Correcting regex read from restraint metadata file.
teemtee/tmt pull request #1110
Opened 2022-03-21 10:53 UTC by pfdaly

The regex used to read from the Restraint metadata file to populate the 'require' field in the main.fmf has been updated from 'repoRequires' to 'dependencies'. Result of test execution below.

Command used:
`tmt test import --restraint --no-nitrate`

metadata file content:
```
[General]
name=stress/stress-ng
owner=Jeff Bastian <jbastian@redhat.com>
description=Run stress-ng tests
license=GPLv2
confidential=no
destructive=no

[restraint]
entry_point=bash ./runtest.sh
dependencies=wget;git;time;patch;bzip2;autoconf;glib2-devel;make;gettext;automake;gcc;libtool;bison;flex;libcap-devel;zlib-devel;beakerlib
softDependencies=dmidecode;rpmdevtools;libaio-devel;libattr-devel;libbsd-devel;libgcrypt-devel;libsctp-devel;keyutils-libs;beakerlib-redhat
repoRequires=cki_lib
```

Generated main.fmf file content:

```
[root@pdaly child]# cat main.fmf 
summary: Run stress-ng tests
description: |
    Just run 'tmt --help' to make sure the binary is sane.
    This is really that simple. Nothing more here. Really.
contact: Jeff Bastian <jbastian@redhat.com>
framework: beakerlib
require:
  - wget
  - git
  - time
  - patch
  - bzip2
  - autoconf
  - glib2-devel
  - make
  - gettext
  - automake
  - gcc
  - libtool
  - bison
  - flex
  - libcap-devel
  - zlib-devel
  - beakerlib
recommend:
  - dmidecode
  - rpmdevtools
  - libaio-devel
  - libattr-devel
  - libbsd-devel
  - libgcrypt-devel
  - libsctp-devel
  - keyutils-libs
  - beakerlib-redhat
extra-summary: stress/stress-ng
extra-task: stress/stress-ng
[root@pdaly child]#
```

2022-03-22 11:42 UTC, pfdaly commented
Hi @lukaszachy, this is the code fix for #1106 which was an issue identified with #1043.
I'm not sure why the centos-stream-x86_64 testing is currently failing, it looks to be related to Podman as opposed to my change.

2022-03-24 07:41 UTC, lukaszachy requested changes
Hi @pfdaly, Change looks good however could you please update the test? In test metadata is still 'repoRequires' which is ignored now. Could you also extend the restraint part of the test to check for all values it should add?

2022-03-24 12:51 UTC, lukaszachy approved these changes

2022-03-24 13:06 UTC, merged

2022-03-24 13:06 UTC, lukaszachy commented
Thank you for the PR, changed commit message a bit, squashed and merged