Detect component from general plan during import
teemtee/tmt pull request #1155
Opened 2022-05-04 15:15 UTC by lukaszachy

Disabled by default, use --general to enable.
Complementary to export --general which keeps only Genereral plans for
specified components

Fix #607

2022-05-13 11:22 UTC, lukaszachy commented
I've realized that components from general plan should override components from test case (which was set by tcms-submit according to the makefile). 
UC1 - Intergration test was linked to another component's General plan without updating makefile/case components
UC2 - Test was cloned for another component and old components were intact (they are not actively used by current tooling)

For both cases possible `tmt test export --nirate --general` will remove more general plans than it should

2022-05-16 14:52 UTC, hegerj requested changes

2022-05-16 14:55 UTC, lukaszachy commented on tmt/convert.py
> +        for nitrate_plan in [plan for plan in testcase.testplans]:
good catch

2022-05-16 14:57 UTC, lukaszachy commented
List comprehension removed and rebased to the current main branch.

2022-05-17 07:51 UTC, hegerj approved these changes
LGTM

2022-05-19 17:07 UTC, psss approved these changes
Looks fine, thanks for the improvement. What about using a non-white-space match `r"(\S+?)\s*/\s*General"` for the component name instead of anything to ignore possible spaces at the beginning?

2022-05-19 17:15 UTC, lukaszachy commented
non-white-space matching looks better.

2022-05-19 20:03 UTC, merged