Require qemu dependencies for other architectures
teemtee/tmt pull request #1223
Opened 2022-05-31 16:36 UTC by psss

In order to make the user experience as fluent as possible for
non-intel arches supported in `testcloud` as well let's require
corresponding qemu packages.

2022-05-31 16:37 UTC, psss commented
Hm, or should this rather go to `testcloud` instead?

2022-06-01 09:31 UTC, lukaszachy commented
Could those be "weak" dependencies? Currently we don't require even x86_64.

Also those are not available on rhel-8 (nor epel)

2022-06-01 09:32 UTC, lukaszachy requested changes
not available in epel/rhel-8

2022-06-01 13:18 UTC, lukaszachy commented
> > By chain of dependencies.
> 
> Do you suggest to recommend it directly?

Would be better, IMO. tmt recommend it for better UX so why depend on 3rd party chain.

2022-06-01 13:28 UTC, psss commented
Makes sense, updated.

2022-06-02 11:55 UTC, lukaszachy approved these changes

2022-06-02 13:03 UTC, merged