initial draft of integration tests for polarion
teemtee/tmt pull request #1358
Opened 2022-07-22 07:53 UTC by jscotka

2022-07-25 13:57 UTC, KwisatzHaderach approved these changes
Good job getting requre to work with pylero.

2022-07-25 13:57 UTC, KwisatzHaderach commented on tests/integration/data/polarion/existing_testcase/main.fmf
> +  - implements: https://polarion.engineering.redhat.com/polarion/#/project/RedHatEnterpriseLinux7/workitem?id=RHEL-293393
either make it .example like ^ or IMO you can remove this line completely so we are not putting internal links on public github

right now it doesn't use the links for anything anyway

2022-08-23 08:49 UTC, lukaszachy requested changes
LGTM but please rebase to the current main.

2022-08-23 10:49 UTC, psss commented
Hm, I'm not really sure about the binary data. The `PolarionBase.test.yaml` file has over 2 MB. @jscotka, if there is a slight change of the call, would the large blob be regenerated or not? If the expected Polarion data are expected to be in megabytes I'd strongly vote for a separate repository for these integration tests. Perhaps we could create a https://github.com/teemtee/tests repo for extra test coverage which is not suitable for the main repo?

2022-08-23 21:00 UTC, thrix commented
> Hm, I'm not really sure about the binary data. The `PolarionBase.test.yaml` file has over 2 MB. @jscotka, if there is a slight change of the call, would the large blob be regenerated or not? If the expected Polarion data are expected to be in megabytes I'd strongly vote for a separate repository for these integration tests. Perhaps we could create a https://github.com/teemtee/tests repo for extra test coverage which is not suitable for the main repo?

Another idea: couldn't we compress this data, from 2MB we get 200kB with xz, what is definitely better?

2022-08-23 21:02 UTC, thrix commented
> > Hm, I'm not really sure about the binary data. The `PolarionBase.test.yaml` file has over 2 MB. @jscotka, if there is a slight change of the call, would the large blob be regenerated or not? If the expected Polarion data are expected to be in megabytes I'd strongly vote for a separate repository for these integration tests. Perhaps we could create a https://github.com/teemtee/tests repo for extra test coverage which is not suitable for the main repo?
> 
> Another idea: couldn't we compress this data, from 2MB we get 200kB with xz, what is definitely better?

And second idea, what Polarion objects did we use, couldn't we spare some space also using some different data?

2022-08-24 06:40 UTC, lukaszachy commented
Another way is to use git lfs to store those files - https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage

2022-09-12 09:14 UTC, jscotka commented
> Hm, I'm not really sure about the binary data. The `PolarionBase.test.yaml` file has over 2 MB. @jscotka, if there is a slight change of the call, would the large blob be regenerated or not? If the expected Polarion data are expected to be in megabytes I'd strongly vote for a separate repository for these integration tests. Perhaps we could create a https://github.com/teemtee/tests repo for extra test coverage which is not suitable for the main repo?

another repo is also possible, but probbaly not ideal case. I think there shouldnt ne much changes often. but I understand it is more data than expected. Especially it is exactly case, where when TMT sync data into/back test machines causes issues, because it is bigger than obvious.

2022-09-12 09:15 UTC, jscotka commented
> > Hm, I'm not really sure about the binary data. The `PolarionBase.test.yaml` file has over 2 MB. @jscotka, if there is a slight change of the call, would the large blob be regenerated or not? If the expected Polarion data are expected to be in megabytes I'd strongly vote for a separate repository for these integration tests. Perhaps we could create a https://github.com/teemtee/tests repo for extra test coverage which is not suitable for the main repo?
> 
> Another idea: couldn't we compress this data, from 2MB we get 200kB with xz, what is definitely better?

yep, possible, but from perspective of data, have it compressed means that it will changes everything when changed, without compression there is change that there will be just some diff.

2022-09-12 10:48 UTC, jscotka commented
> > > Hm, I'm not really sure about the binary data. The `PolarionBase.test.yaml` file has over 2 MB. @jscotka, if there is a slight change of the call, would the large blob be regenerated or not? If the expected Polarion data are expected to be in megabytes I'd strongly vote for a separate repository for these integration tests. Perhaps we could create a https://github.com/teemtee/tests repo for extra test coverage which is not suitable for the main repo?
> > 
> > 
> > Another idea: couldn't we compress this data, from 2MB we get 200kB with xz, what is definitely better?
> 
> And second idea, what Polarion objects did we use, couldn't we spare some space also using some different smaller data?

It is also possible, that we can use these requre data analyse and try to improve polarion usage, what also will lead to higher speed or less data usage of TMT itself. But these optimization are probably not current goal.

2022-10-14 10:26 UTC, jscotka commented
> 

Hi @thrix finally I've done smaller hack to store binary data as separate files and compress them to one archive, so that core data are clear and binary data are also easier to look at and see what is there, just need to decompress them before tests.  What is part of TMT polarion testplan. It seems clear and it is <100kb of data. So I think it is now nice solution.

And you are right theoretically I can filter objects form polarion to just these what we really use, but it could be very hard to do. theoretically as post-processing these data from polarion.

2022-10-14 11:43 UTC, KwisatzHaderach approved these changes

2022-10-14 11:43 UTC, KwisatzHaderach commented on plans/integration/create_pylero_cfg.sh
> +svn_repo=https://polarion.examplee.com/repo
not like it matters, but you have a typo here 'examplee'

2022-10-14 11:43 UTC, KwisatzHaderach commented on tests/integration/data/polarion/existing_dryrun_testcase/main.fmf
> +  - implements: https://polarion.engineering.redhat.com/polarion/#/project/RHELBASEOS/workitem?id=BASEOS-12730
this line should probably not be here, internal link

2022-10-14 11:54 UTC, KwisatzHaderach approved these changes

2022-10-24 12:35 UTC, psss commented
Thanks for minimizing the test data! After a short discussion with @jscotka we agreed to give a try to a dedicated tests repository. This will serve as a

 * space for tests which need large or binary data
 * dogfooding the fresh remote plan import feature

The repository has been created here:

 * https://github.com/teemtee/tests

Packit is enabled so we can enable testing of the changes in the repo itself as well.

2022-10-25 19:16 UTC, jscotka commented
> Thanks for minimizing the test data! After a short discussion with @jscotka we agreed to give a try to a dedicated tests repository. This will serve as a
> 
>     * space for tests which need large or binary data
> 
>     * dogfooding the fresh remote plan import feature
> 
> 
> The repository has been created here:
> 
>     * https://github.com/teemtee/tests
> 
> 
> Packit is enabled so we can enable testing of the changes in the repo itself as well.

So, moved tests to https://github.com/teemtee/tests/pull/1

2022-10-27 10:33 UTC, jscotka commented
closing this PR, as we use remote plan for polarion tests

2022-10-27 10:33 UTC, closed without merging