Teach schema validation tests to peek into other trees
teemtee/tmt pull request #1434
Opened 2022-08-13 12:53 UTC by happz

There are some "hidden" trees in tmt's repo, trees that are tailored for
various tests. These are not covered by schema-validation unit test,
this patch adds necessary code to enable this coverage.

It's left disabled, though, because plenty of theese trees are malformed
on purpose, and therefore cause a test failure. Before enabling the test
in general, we need a way how to mark a tree as "broken, nothing to see
here, move on" *for this test only* - we do not want `tmt lint` to skip
it, just the unit test.

2022-08-15 10:52 UTC, ukulekek approved these changes
LGTM

2022-08-23 13:43 UTC, thrix requested changes
small nitpick found, otherwise LGTM

2022-08-27 21:51 UTC, happz commented on tests/unit/test_schemas.py
> +    # Ad hoc construction, but here me out: there are small, custom-tailored fmf tress
Fixed.

2022-08-29 07:23 UTC, thrix approved these changes

2022-08-29 07:24 UTC, merged