Require `libvirt-daemon-config-network` as well
teemtee/tmt pull request #1454
Opened 2022-08-19 12:05 UTC by psss

In order to provide a fluent user experience when using `virtual`
provision with the `system` connection, include this extra package
in `tmt-provision-virtual` dependencies to make it working out of
the box. Add test coverage ensuring that all dependencies are
correctly installed.

2022-08-19 12:08 UTC, psss commented
Another option could be to add `libvirt-daemon-config-network` to `python3-testcloud` requires. @frantisekz, any thoughts on this?

2022-08-19 13:03 UTC, psss commented
I considered that as well but the thing is that the `/plans/provision/virtual` creates a new vm and inside it installs `tmt` packages. This allows to reproduce the missing dependency as well. On the other hand, `/tests/provision/virtual.testcloud` is now run under the `/plans/features/basic` which can be executed on user laptop or full plan vm with its own adjustments. Perhaps, would it make sense to execute `/tests/provision/virtual.testcloud` also under `/plans/provision/virtual`?

2022-08-19 13:32 UTC, lukaszachy commented
I see. So the real test is the plan /plans/provision/virtual itself. Lets keep it separated and we can shuffle things in #1171.

From my PoV this can be risk for tests/full as we are effectively 3 levels of nested VM (VM with tested tmt -> run with provider virtual -> spawned VM in the test)

2022-08-19 13:43 UTC, lukaszachy approved these changes

2022-08-19 13:49 UTC, psss commented
> I see. So the real test is the plan /plans/provision/virtual itself. Lets keep it separated and we can shuffle things in #1171.

Ack.

> From my PoV this can be risk for tests/full as we are effectively 3 levels of nested VM (VM with tested tmt -> run with provider virtual -> spawned VM in the test)

Hm, good point. Let's see how it works. If it's too slow we'll need to find a better way.

2022-08-22 15:29 UTC, lukaszachy commented
Hm, I've tried to run this in tests/full on my laptop and I see error for 'session':
``` out: libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory ```

'system' fails to boot but I see no error so I suspect that 60s timeout to boot is not long enough

2022-08-23 07:16 UTC, lukaszachy commented
I'll give it a shot to see why virtqemud-sock happens.

2022-08-23 11:12 UTC, lukaszachy requested changes
When I run tmt command as user (not as a root as this test does) the socket was not needed nor was necessary to start libvirtd)

We should fix the test :) 
Also - Shouldn't we move the plan to 'data' so test makes sure that it creates new VM?
Because without _fresh_ vm (or if libvirtd is already started) issue is mitigated.

2022-08-24 11:15 UTC, psss commented
> When I run tmt command as user (not as a root as this test does) the socket was not needed nor was necessary to start libvirtd) We should fix the test :)

Good point. Test updated to run under a regular user which covers the real use case much better.

> Also - Shouldn't we move the plan to 'data' so test makes sure that it creates new VM? Because without _fresh_ vm (or if libvirtd is already started) issue is mitigated.

Do you suggest to create a new separate plan for this single test? Not sure if it's worth it for now. What about running the test as the first one under the `/plans/provision/virtual` plan? I've updated `order` accordingly.

2022-08-24 11:29 UTC, lukaszachy commented
> Do you suggest to create a new separate plan for this single test? Not sure if it's worth it for now. What about running the test as the first one under the `/plans/provision/virtual` plan? I've updated `order` accordingly.

Not only that. Nested tests/plan make it easier for reporting / asserting passes. Lets say if there is problem with testcloud itself. /plans/provision/virtual errors and whole run exists with '2' (== no next plan is ran)

However if there test uses nested plan, then tmt has to be seriously broken for the top tmt to exit with 2 and stop execution.
And one can assert outcomes in the test.

But lets keep as is. Above should be addressed soon but in different pr.

2022-08-24 11:31 UTC, lukaszachy approved these changes

2022-08-24 12:07 UTC, psss commented
Thanks for the detailed explanation. Makes sense. For this case, however, there's one more thing which would have to be covered for the plan nested under `data`: We need to install fresh `tmt` packages inside the provisioned vm, which is currently handled using `how=full` adjust rule for `/plan/provision/*` plans only.

2022-08-24 13:21 UTC, merged

2022-09-09 11:04 UTC, frantisekz commented
FYI: I've added libvirt-daemon-config-network to testcloud as well, will be part of next micro release next week, thanks for catching this!