Add Polarion as a source for test case import
teemtee/tmt pull request #1502
Opened 2022-09-09 13:59 UTC by KwisatzHaderach

Doesn't import anything new (compared to other methods) however some teams heave cases only in Polarion and this provides an easy way to pull data with --polarion-case-id, when other methods of searching (id, extra-nitrate, extra-task) would not work.
Also pulls id from Polarion if it is present or generates (and exports) a new one if it is not.

2022-09-26 11:16 UTC, happz approved these changes

2022-09-26 13:33 UTC, psss requested changes
Thanks for implementing this! Looks good in general. Added a few minor suggestions.

2022-09-26 13:33 UTC, psss commented on docs/examples.rst
> +library (described in `Export tests`_) and enable with ``--polarion`` flag.
```suggestion
library (described in `Export tests`_) and enable it with the ``--polarion`` flag.
```

2022-09-26 13:33 UTC, psss commented on tmt/cli.py
> +    help='Import test metadata from Polarion')
```suggestion
    help='Import test metadata from Polarion.')
```

This applies for all options.

2022-09-26 13:33 UTC, psss commented on tmt/cli.py
> +    polarion ..... summary, enabled, assignee, id, component, tags, description, links
```suggestion
    polarion ..... summary, enabled, assignee, id, component, tag, description, link
```

2022-09-26 13:33 UTC, psss commented on tmt/convert.py
> +        raise ConvertError('Failed to find test case in Polarion')
```suggestion
        raise ConvertError('Failed to find test case in Polarion.')
```

See also the [hint](https://tmt.readthedocs.io/en/latest/contribute.html#introduction) for error messages.

2022-09-26 13:33 UTC, psss commented on tmt/convert.py
> +            tier_match = re.match(r'^Tier ?(?P<num>\d+)$', tag, re.I)
What about creating a small shared function to handle the tier level extraction instead of duplicating the nitrate code here?

2022-09-26 13:33 UTC, psss commented on tmt/convert.py
> +        server_url = str(polarion_case._session._server.url)
What about handling the missing/present slash at the end here instead of doing it twice below?

2022-09-29 13:22 UTC, psss approved these changes
Thanks for addressing all comments! Looks good now.

2022-09-29 14:42 UTC, merged