Review all uses of Any and refer to relevant issues
teemtee/tmt pull request #1603
Opened 2022-10-17 19:55 UTC by happz

Some `Any` are useful, for some I filed either an issue or an alias to imrpvoe the situation for future devels.

2022-10-18 12:09 UTC, lukaszachy commented on tmt/steps/provision/testcloud.py
> -                    clean.error(f"Failed to remove '{image}'.", shift=2)
Good catch.

2022-10-19 14:10 UTC, psss requested changes
Just one tiny change.

2022-10-19 14:14 UTC, happz commented on tmt/export.py
> +        polarion_case_id: Optional[str] = None) -> PolarionTestCase:
Correct, it's `Optional`.

2022-10-19 14:22 UTC, psss commented on tmt/export.py
> +        polarion_case_id: Optional[str] = None) -> PolarionTestCase:
Ok updated.

2022-10-19 15:44 UTC, merged