Warn user about data erasing after prepare step
teemtee/tmt pull request #1653
Opened 2022-11-01 15:55 UTC by adiosnb

Closes #964

2022-11-01 16:07 UTC, lukaszachy approved these changes
+1 but lets wait on @psss if wording is 100% correct.

2022-11-03 14:33 UTC, psss requested changes
Thanks for putting this together. Looks ok, I've found two typos and suggest to omit the unnecessary implementation details at the end. What do you think?

2022-11-03 14:33 UTC, psss commented on spec/plans/prepare.fmf
> +        files for the testing in the ``exeute`` step, you need to
```suggestion
        files needed for testing during the ``execute`` step,
```

2022-11-03 14:33 UTC, psss commented on spec/plans/prepare.fmf
> +        move or copy them into ``${TMT_TEST_DATA}`` directory. Only
```suggestion
        move or copy them into ``${TMT_PLAN_DATA}`` directory. Only
```

2022-11-03 14:33 UTC, psss commented on spec/plans/prepare.fmf
> +        files in this directory are pulled back to the local machine
```suggestion
        files in this directory are guaranteed to be preserved.
```

I would probably skip the rest of the paragraph as those are rather implementation details, not interesting for the user and hard to explain precisely/correctly in a short sentence.

2022-11-04 08:03 UTC, merged