Dockerfile request matching tmt version
teemtee/tmt pull request #1751
Opened 2022-12-09 14:22 UTC by lukaszachy

Packit is producing y+1.dev versions however we want to have one with matching release in the container.

No idea yet how to avoid the manual 'copr build' step :/

2022-12-14 11:57 UTC, psss requested changes
As agreed on the chat, let's pick the latest `tmt` from Fedora stable repos instead. This will also remove the need for the manual `copr` build.

2023-11-21 08:58 UTC, psss commented
Any plans with this one, @lukaszachy?

2023-11-21 14:07 UTC, lukaszachy commented
@psss If we go by previous agreement it means one needs to remember building a new image about a week after the release.


I'll check if we didn't solve the problem by moving to hatch. Or if there isn't simpler fix.

Waiting means we will forget.

2023-11-21 14:36 UTC, psss commented
> @psss If we go by previous agreement it means one needs to remember building a new image about a week after the release.

Yeah, using `updates-testing` could bit a faster, but still, one has to remember to finish it.

> I'll check if we didn't solve the problem by moving to hatch. Or if there isn't simpler fix.

What about installing the latest non-dev release from the copr repo? Could the exact rpm naming be used somehow?

2024-01-24 12:01 UTC, psss commented
> What about installing the latest non-dev release from the copr repo? Could the exact rpm naming be used somehow?

This seems to be working as expected:

```
# dnf install tmt-[0-9].[0-9][0-9].[0-9]*
Last metadata expiration check: 1:51:30 ago on Wed Jan 24 10:07:14 2024.
Dependencies resolved.
==============================================================================================================================
 Package                            Arch    Version                   Repository                                         Size
==============================================================================================================================
Installing:
 tmt                                noarch  1.30.0-1.fc39             copr:copr.fedorainfracloud.org:group_teemtee:tmt  803 k
```

It picks the latest stable version from the copr repo even if there is a newer `dev` version:

```
# dnf install tmt
Last metadata expiration check: 1:53:06 ago on Wed Jan 24 10:07:14 2024.
Dependencies resolved.
==============================================================================================================================
 Package                         Arch   Version                        Repository                                        Size
==============================================================================================================================
Installing:
 tmt                             noarch 1.31.dev49+gdf8303f1-main.fc39 copr:copr.fedorainfracloud.org:group_teemtee:tmt 825 k
```

@lukaszachy, let's try it this way?

2024-01-24 15:46 UTC, lukaszachy commented
@psss LGTM (I can't provide approval for (according to the github) my PR)

2024-01-24 16:12 UTC, psss commented
> @psss LGTM (I can't provide approval for (according to the github) my PR)

Good, thanks for having a look!

2024-01-24 16:35 UTC, psss commented
/packit test -i full

2024-01-25 10:41 UTC, psss commented
/packit test -i

2024-01-25 11:37 UTC, merged