Adds "full name" guest property for multihost logging
teemtee/tmt pull request #1815
Opened 2023-01-25 10:12 UTC by happz

It's guest name with added role, to better identify the guest among its peers.

2023-02-03 17:35 UTC, thrix commented
@happz could we add some unit test for this maybe?

I could not find where would this be used in #1790, do you have some example how it would look like please?

2023-02-03 17:36 UTC, thrix requested changes
A small unit test would be nice, so we have this covered and can reasonable change as needed.

2023-02-04 09:59 UTC, happz commented
> @happz could we add some unit test for this maybe?
> 
> I could not find where would this be used in #1790, do you have some example how it would look like please?

I believe it's this line: https://github.com/teemtee/tmt/pull/1790/files#diff-d9422da1a3efb9209a7d4beb7d824f85a19e5abe91fb239f74806847d88db266R1366

It refers to `guest.id` which, IIRC, I decided to rename to `full_name`, as `id` sounded too vague.

2023-02-04 10:04 UTC, happz commented
> A small unit test would be nice, so we have this covered and can reasonable change as needed.

Done.

2023-02-07 10:42 UTC, lukaszachy approved these changes

2023-02-07 11:49 UTC, psss approved these changes
Looks good.

2023-02-07 12:00 UTC, thrix approved these changes
LGTM, thanks for adding the test

2023-02-07 12:00 UTC, merged