Adds logging "context", i.e. prefix to add to each message
teemtee/tmt pull request #1817
Opened 2023-01-25 12:14 UTC by happz

Each logger can now attach a list of strings representing an optional "context" to each message generated by the said logger. The list would then be added to each message as a prefix.

The goal is to "taint" messages generated by various logger in the multithreaded environment dictated by multihost support. At the beginning, messages produced by phases running on different guests would be prefixed by the guest name, to allow later inspection.

Part of the effort in https://github.com/teemtee/tmt/pull/1790.

2023-02-03 17:52 UTC, thrix commented
I am thinking if the context should not be rather rendered somehow else, as a prefix, while looking at #1790:

```
    execute
        queued: default-0 on verifier, registrar and agent
        
        queue tick #0: default-0 on verifier, registrar and agent
        [verifier] queued
        [verifier] how: tmt
        [registrar] queued
        [verifier] order: 50
        [registrar] how: tmt
        [agent] queued
        [verifier] exit-first: False
        [registrar] order: 50
        [registrar] exit-first: False
        [agent] how: tmt
        [agent] order: 50
        [agent] exit-first: False
        [verifier] finished
```

looks it breks a lot the current view.

How hard would be to print the tags from the end of the screen?

```
    execute
        how: tmt                             [verifier]
        order: 50                            [verifier]
        how: tmt                            [registrar]
        exit-first: False                    [verifier]
        order: 50                           [registrar]
        exit-first: False                   [registrar]
        how: tmt                                [agent]
        order: 50                               [agent]
        exit-first: False                       [agent]
```

2023-02-03 17:54 UTC, thrix requested changes
needs more discussion on the UX, If we cannot do better, I would rather put the tags after the message, not before it.

2023-02-06 08:55 UTC, happz commented
> needs more discussion on the UX, If we cannot do better, I would rather put the tags after the message, not before it.

I agree UX part needs more discussion. But, for the sake of progress, I'd like to point out that how the context is displayed is orthogonal to how it's managed and/or manipulated, and can be modified later as needed, and this patch is not meant to be the definitive answer WRT output formating, the goal was to introduce the feature to get at least some chance for debugging.

2023-02-07 10:52 UTC, lukaszachy commented
I'm used to  the prefixes so +1 to them. Suffix could be difficult for line breaks, arbitrary length of output (If we add hard line breaks we should also allow users to disable that) and IMO you would need to switch between start/end of the line to get the idea what is happening.

Once we have time to figure out nicer UX we could have ncurses/colors or any other fancy thigs. However at this point prefix is the best option IMO.

2023-02-07 11:08 UTC, happz commented
> How hard would be to print the tags from the end of the screen?
> 
> ```
>     execute
>         how: tmt                             [verifier]
>         order: 50                            [verifier]
>         how: tmt                            [registrar]
>         exit-first: False                    [verifier]
>         order: 50                           [registrar]
>         exit-first: False                   [registrar]
>         how: tmt                                [agent]
>         order: 50                               [agent]
>         exit-first: False                       [agent]
> ```

Definitely harder that what we have here, yet still fairly doable. One issue would be the length of the line, we'd have to guesstimate (`TERM`, `COLS`, maybe `terminfo`, etc.) and not bother with log file, for example. Also multiline strings might be issue, but maybe not that big one. Certainly doable, not as trivial as the very basic setup I kicked off.

It could be also possible to move the prefix to *the beginning* of each line and indent the message minus the space occupied by the prefix, e.g.

```
    execute
[verifier]    how: tmt
[verifier]    order: 50
[registrar]   how: tmt
[verifier]    exit-first: False
...
```

That's not that bad, but I think it might be rotten with issues, e.g. what if guest A is called `foo` and guest B is `Lorem ipsum dolor sit amet`, the indentation needed to accommodate all prefixes, then `execute` is indented in a very weird way given the following lines, so... I guess prefixes are fine to start with, but UX definitely needs more ideas.

2023-02-07 11:09 UTC, lukaszachy approved these changes

2023-02-07 11:12 UTC, lukaszachy commented
Guesstimate of cols is PAIN for me as as user - I have change terminal window quite often. Small window when it is running OK and I expand the window when I need to check what is printed.

2023-02-07 11:55 UTC, thrix commented
> > needs more discussion on the UX, If we cannot do better, I would rather put the tags after the message, not before it.
> 
> I agree UX part needs more discussion. But, for the sake of progress, I'd like to point out that how the context is displayed is orthogonal to how it's managed and/or manipulated, and can be modified later as needed, and this patch is not meant to be the definitive answer WRT output formating, the goal was to introduce the feature to get at least some chance for debugging.

Agreed, just wanted to point out,  I will file an issue for the future

2023-02-07 11:56 UTC, thrix commented
> It could be also possible to move the prefix to _the beginning_ of each line and indent the message minus the space occupied by the prefix, e.g.
> 
> ```
>     execute
> [verifier]    how: tmt
> [verifier]    order: 50
> [registrar]   how: tmt
> [verifier]    exit-first: False
> ...
> ```
> 
> That's not that bad, but I think it might be rotten with issues, e.g. what if guest A is called `foo` and guest B is `Lorem ipsum dolor sit amet`, the indentation needed to accommodate all prefixes, then `execute` is indented in a very weird way given the following lines, so... I guess prefixes are fine to start with, but UX definitely needs more ideas.

Yeah, that is why I rather went with the idea of suffixes, anyway :) it can be resolved later, once we agree on some UX improvements.

2023-02-07 11:58 UTC, thrix approved these changes
Improves the situation in case of multiple roles, even if the UX needs more discussion.

2023-02-07 12:11 UTC, thrix commented
@happz as agreed on the review meeting, let's rename the `context` to `tag` to mitigate confusion.

2023-02-07 12:46 UTC, happz commented
> @happz as agreed on the review meeting, let's rename the `context` to `label` to mitigate confusion.

Done.

2023-02-07 16:53 UTC, psss approved these changes
Looks good, thanks!

2023-02-07 18:24 UTC, merged