Convert provision plugins' step data to our field implementation
teemtee/tmt pull request #1836
Opened 2023-02-06 21:43 UTC by happz

This unites options with plugin *and* guest data, and with inheritance, we also get some options shared among plugins through the step data instead of overriden `options()` methods.

2023-02-06 21:44 UTC, happz commented
Blocked because of `field()` lacking the support for envvars.

2023-06-27 08:14 UTC, psss requested changes
Thanks for the cleanup! Just a few minor suggestions.

2023-06-27 08:14 UTC, psss commented on tmt/steps/provision/__init__.py
> +        help="Specify additional SSH option. "
```suggestion
        help="Specify an additional SSH option. "
```

2023-06-27 10:47 UTC, happz commented on tmt/utils.py
> +    and return ``ping.Quantity`` instead.
Fixed in 2895cbbb.

2023-06-27 10:49 UTC, happz commented on tmt/utils.py
> +    For a field that takes an integer input, but might be also left out,
Fixed in 2895cbbb. It turns out that normalization callbacks should probably accept `Any` as their input, and deal with types in their body.

I'm not sure whether it's necessary to mention the `str` coming from Click, strings are everywhere :)

2023-06-27 10:50 UTC, happz commented on tmt/steps/provision/__init__.py
> +        help="Specify additional SSH option. "
Fixed in 2895cbbb.

2023-06-27 12:49 UTC, psss approved these changes

2023-06-27 12:50 UTC, merged