Expose guest info in results
teemtee/tmt pull request #1903
Opened 2023-03-08 13:53 UTC by happz

This has been prepared, now the export becomes enabled.

2023-03-10 19:22 UTC, thrix requested changes
@happz I am missing some tests, like I would expect this is visible somewhere in results.yml, could we assert it somehow?

2023-03-10 22:29 UTC, happz commented
> @happz I am missing some tests, like I would expect this is visible somewhere in results.yml, could we assert it somehow?

You're correct, the tests are missing. I plan to address that in a follow-up patch, because AFAICT, and many other fields of `results.yaml` are unchecked as well. So, together with the documentation update, I plan to add a PR with some `yq` calls to assert the content of `results.yaml`. My goal is to get such a patch into 1.22, to present a consistent and safe picture when it all gets released - keeing things consistent in every patch turned out to be too much work :( Does this sound acceptable?

2023-03-13 13:19 UTC, janhavlin approved these changes

2023-03-16 18:17 UTC, merged

2023-03-16 18:17 UTC, psss commented
The `el8` failure is irrelevant --> merged.