DRAFT: Move testcloud url guessing logic out of tmt
teemtee/tmt pull request #1914
Opened 2023-03-10 15:25 UTC by frantisekz

testcloud counterpart: https://pagure.io/testcloud/pull-request/144 . 

Adds support for Alma Linux, Rocky Linux, and Oracle Linux. 

testcloud-side, things should be more robust. The one todo I have is for alma url guessing improvement as they have no base mirror/no transparent redirect to the fastest/closest.

@lbrabec took a look at libosinfo and found it insufficient for this use-case (he'll chime in next week with his findings).

Feel free to comment here even about testcloud side of changes.

2023-03-10 15:25 UTC, frantisekz commented
FYI: This will require testcloud bump and release coordination, I'll prepare a build in copr tomorrow or next week.

2023-03-10 15:36 UTC, frantisekz commented
@danmyway this should add all the distros for convert2rhel you've mentioned in https://github.com/teemtee/tmt/pull/651#issuecomment-1326616328 :)

2023-03-10 16:30 UTC, lukaszachy commented
Great, you read my mind! In near future I want to finally put support for downloading internal rhel images (internal plugin) so simplification in the testcloud.py is really appreciated.

The release coordination from tmt PoV is just to wait until testcloud is available and bump our spec/setup.py requirements, right? 

With new testcloud - will something break for older (read: currently released) tmt?

2023-03-13 13:21 UTC, lbrabec commented
> @lbrabec took a look at libosinfo and found it insufficient for this use-case (he'll chime in next week with his findings).

Yeah, I found the libosinfo db to be incomplete, e.g. missing Oracle Linux 9.

2023-03-18 23:57 UTC, frantisekz commented
> > @danmyway this should add all the distros for convert2rhel you've mentioned in [#651 (comment)](https://github.com/teemtee/tmt/pull/651#issuecomment-1326616328) :)
> 
> Oh, that is really cool! Thanks @frantisekz! Let me know, if I can be of any help.

@danmyway It'd be great if you could give it a try now: testcloud from https://copr.fedorainfracloud.org/coprs/frantisekz/testcloud-wip/ and tmt with this PR included. Fingers crossed everything works :)

2023-03-21 08:32 UTC, psss commented
Thanks for the updated package. Checked with `python3-testcloud-0.9.1-1.fc37.noarch`, now works fine after fixing a typo in 8445eed1. We should handle invalid images in a more user friendly way:

```
tmt run -vvv provision -h virtual -i wrong login finish

Traceback (most recent call last):
  File "/usr/bin/tmt", line 20, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1689, in invoke
    return _process_result(rv)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1626, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tmt/cli.py", line 351, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.11/site-packages/tmt/base.py", line 2657, in go
    plan.go()
  File "/usr/lib/python3.11/site-packages/tmt/base.py", line 1660, in go
    step.go()
  File "/usr/lib/python3.11/site-packages/tmt/steps/provision/__init__.py", line 1288, in go
    phase.go()
  File "/usr/lib/python3.11/site-packages/tmt/steps/provision/testcloud.py", line 635, in go
    self._guest.start()
  File "/usr/lib/python3.11/site-packages/tmt/steps/provision/testcloud.py", line 372, in start
    self.image_url = self._guess_image_url(self.image_url)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tmt/steps/provision/testcloud.py", line 278, in _guess_image_url
    url = testcloud.util.get_image_url(name.lower().strip(), self.arch)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/testcloud/util.py", line 82, in get_image_url
    raise exceptions.TestcloudImageError
testcloud.exceptions.TestcloudImageError
```

Hm, we're catching all exceptions when calling `get_image_url()`. Any idea why this has not been catched?

2023-03-21 08:48 UTC, psss requested changes
Could you please correctly handle the exception when an invalid image is provided? Also would you extend the module docs with the newly supported image names so that they are discoverable using `tmt run provision --how virtual --help`? Thanks.

2023-03-22 14:45 UTC, psss approved these changes
Thanks for the docs & `testcloud` update. Now everything works as expected and the exception for invalid images is correctly catched as well.

2023-03-22 17:01 UTC, lukaszachy commented
@psss @frantisekz I'm trying 
tmt-1.22.dev-1.20230322153017921774.pr1914.50.g852938c.fc37.noarch
python3-testcloud-0.9.1-1.fc37.noarch

but it `fail: Failed to connect in 60s.`. Virsh shows the VM is running and I can login to the console however ssh isn't running there (and systemctl start didn't help tmt to connect in time)

Also, are we ready for rfe to support non-rpm installs of require/recommend? ;)

2023-03-22 17:34 UTC, frantisekz commented
> @psss @frantisekz I'm trying `tmt -vvv run provi -h virtual -i ubuntu` with tmt-1.22.dev-1.20230322153017921774.pr1914.50.g852938c.fc37.noarch python3-testcloud-0.9.1-1.fc37.noarch
> 
> but it `fail: Failed to connect in 60s.`. Virsh shows the VM is running and I can login to the console however ssh isn't running there (and systemctl start didn't help tmt to connect in time)
> 

Hmm, from a quick look, it worked for me with plain testcloud (both system and session modes). However, I have pre-cached earlier 22.10 image, while downloading a fresh image for the latest Ubuntu will get you 22.10.1. This might be the cause, I'll take a closer look tomorrow.

> Also, are we ready for rfe to support non-rpm installs of require/recommend? ;)

I am afraid I am not sure what do you have in mind atm, but, there is never enough of RFEs ;)

2023-03-23 08:05 UTC, lukaszachy commented
> > @psss @frantisekz I'm trying `tmt -vvv run provi -h virtual -i ubuntu` with tmt-1.22.dev-1.20230322153017921774.pr1914.50.g852938c.fc37.noarch python3-testcloud-0.9.1-1.fc37.noarch
> > but it `fail: Failed to connect in 60s.`. Virsh shows the VM is running and I can login to the console however ssh isn't running there (and systemctl start didn't help tmt to connect in time)
> 
> Hmm, from a quick look, it worked for me with plain testcloud (both system and session modes). However, I have pre-cached earlier 22.10 image, while downloading a fresh image for the latest Ubuntu will get you 22.10.1. This might be the cause, I'll take a closer look tomorrow.

Thanks. I've tried on my laptop (in virtualenv though) and behaves the same.

In the console (of VM) I see: `cloud-init[1066]: Failed to reload sshd.service: Unit sshd.service not found`

Once I login (via virsh):
```
root@default-0:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:2a:6d:8c brd ff:ff:ff:ff:ff:ff
    inet 172.17.2.15/24 metric 100 brd 172.17.2.255 scope global dynamic enp0s3
       valid_lft 86299sec preferred_lft 86299sec
    inet6 fec0::5054:ff:fe2a:6d8c/64 scope site dynamic mngtmpaddr noprefixroute 
       valid_lft 86301sec preferred_lft 14301sec
    inet6 fe80::5054:ff:fe2a:6d8c/64 scope link 
       valid_lft forever preferred_lft forever
3: enp0s30: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 52:54:00:12:34:56 brd ff:ff:ff:ff:ff:ff

root@default-0:~# dhclient
root@default-0:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:2a:6d:8c brd ff:ff:ff:ff:ff:ff
    inet 172.17.2.15/24 metric 100 brd 172.17.2.255 scope global dynamic enp0s3
       valid_lft 86219sec preferred_lft 86219sec
    inet6 fec0::5054:ff:fe2a:6d8c/64 scope site dynamic mngtmpaddr noprefixroute 
       valid_lft 86221sec preferred_lft 14221sec
    inet6 fe80::5054:ff:fe2a:6d8c/64 scope link 
       valid_lft forever preferred_lft forever
3: enp0s30: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:12:34:56 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s30
       valid_lft 86352sec preferred_lft 86352sec
    inet6 fec0::5054:ff:fe12:3456/64 scope site dynamic mngtmpaddr 
       valid_lft 86353sec preferred_lft 14353sec
    inet6 fe80::5054:ff:fe12:3456/64 scope link 
       valid_lft forever preferred_lft forever
```

After 'dhclient' call ssh into the VM works (ssh gets activated by socket so no need to start ssh manually)



> 
> > Also, are we ready for rfe to support non-rpm installs of require/recommend? ;)
> 
> I am afraid I am not sure what do you have in mind atm, but, there is never enough of RFEs ;)

Just grep the sources for all 'rpm', 'yum' or 'dnf' usage we will have to (finally) generalize to support non-RPM flavours.

2023-03-23 08:10 UTC, happz commented
> > > Also, are we ready for rfe to support non-rpm installs of require/recommend? ;)
> > 
> > 
> > I am afraid I am not sure what do you have in mind atm, but, there is never enough of RFEs ;)
> 
> Just grep the sources for all 'rpm', 'yum' or 'dnf' usage we will have to (finally) generalize to support non-RPM flavours.

That would be very nice. ~~I~~ a friend of mine is often playing with tmt in an Ubuntu WSL. That's actually why ~~I~~ a friend of mine submitted the guest facts patch, it started as a way to expose the package manager command to other parts of tmt, not just `prepare/install` :)

2023-03-23 08:58 UTC, psss commented
Right, those are all good points!

* So `ubuntu` image does not work (but it does not work with released `tmt` and `testcloud` either)
* If the image has `rsync` installed and connection is fixed it could work partially (e.g no package installation)
* But otherwise, for proper/full support, we need non-rpm changes (not a big priority though)
* And the guest facts in #1890 looks very nice!

All in all, I guess, these should not block merging the PR, except the fact that we mention `ubuntu` (and others) in the list of supported images. What now? Mention them but with a warning that support for them is very limited as for now? Or omit them completely?

2023-03-23 16:58 UTC, lukaszachy commented
I'd say we should document that non-RPM distro are not very well supported but that is true right now.
This PR just _could_ bring false hope that if tmt mentions say 'ubuntu' as image to provision it is supported for all usage.

With that said - merge it. We can add note to the docs and that's it (for now).

2023-03-24 07:19 UTC, psss commented
> With that said - merge it. We can add note to the docs and that's it (for now).

Ack. Docs extended with note in f2d51b06. Bodhi updates reached `stable` so now we should get green jobs even with the updated `Requires`. Let's see...

2023-03-24 15:40 UTC, merged