Proper support for duration format
teemtee/tmt pull request #1972
Opened 2023-04-04 13:08 UTC by lukaszachy

We claim to support same format as `sleep` commands so let's actually do it.

2023-04-05 12:02 UTC, happz approved these changes

2023-04-05 12:52 UTC, psss requested changes
Looks good, we just need to extend the schema as well:

    warn: /tests/core/smoke:duration - '1s 2s' does not match '^[0-9]+[smhd]$'

Proposing also a minor docs enhancement in 4a3ef7554962b2e7c7264c8ca3ba1f63092ee2e8.

2023-04-05 14:23 UTC, KwisatzHaderach commented on tmt/utils.py
> +    for part in re.findall(r'(\d+) *([smhd]?)', str(duration)):
```suggestion
    for number, suffix in re.findall(r'(\d+) *([smhd]?)', str(duration)):
```
then you can skip the following line

2023-04-12 10:08 UTC, lukaszachy commented on tests/unit/test_utils.py
> +    assert duration_to_seconds('1 m2   m') == 180
Exactly. The outcome of adjust / inheritance doesn't need to be human readable (messing with spaces is pain) And when we loose the human readability requirement.... IF someone wants to write it this way, well ... maybe we could add hook into tmt test show the final human readable value.

2023-04-12 10:15 UTC, lukaszachy commented on tmt/utils.py
> +    for part in re.findall(r'(\d+) *([smhd]?)', str(duration)):
Right. done in 6dc708db

2023-04-13 20:50 UTC, psss approved these changes
Thanks for the nice fix & improvement! Spec example simplified in 16dc695a.

2023-04-13 20:58 UTC, KwisatzHaderach approved these changes

2023-04-14 05:26 UTC, merged