Convert gitlab private namespace into dist-git url
teemtee/tmt pull request #2036
Opened 2023-04-28 14:52 UTC by lukaszachy

Workaround for #1818 so exported tests can be fetched without authenfication at the cost. This will work while the sync is being done.

2023-05-02 12:00 UTC, psss requested changes
Sounds like a reasonable workaround to me. Just two minor comments.

2023-05-03 07:35 UTC, lukaszachy commented on tmt/utils.py
> +    # git@gitlab.com:redhat/rhel
Fixed in 235d38ed

2023-05-03 07:35 UTC, lukaszachy commented on tmt/utils.py
> +    matched = re.match(r'(?:git@|https://)gitlab.com[:/]redhat/rhel(/.*)\.git', url)
Fixed in 235d38ed

2023-05-03 08:05 UTC, happz approved these changes

2023-05-04 17:03 UTC, psss approved these changes
Thanks, now looks good!

2023-05-04 19:32 UTC, merged