Try out the new packit feature `manual_trigger`
teemtee/tmt pull request #2146
Opened 2023-06-09 13:10 UTC by psss

This would allow us to run longer plans only upon request. Should be available in the production instance on Tuesday. Let's see how it works! ;-)

2023-06-15 06:05 UTC, psss commented
@lachmanfrantisek, it seems that statuses are not correct. There are two jobs defined, one should be executed without the manual trigger and the other one upon request. The `basic` one looks ok as `Queued` as it wait for the manual trigger. But there are no results from `core`. Could you please have a look?

2023-06-16 09:52 UTC, psss commented
/packit test --identifier core

2023-06-16 11:06 UTC, psss commented
It seems that even after manual comment it stays in `The task was accepted` state:
https://github.com/teemtee/tmt/pull/2146/checks?check_run_id=14317557767

2023-06-19 13:33 UTC, psss commented
/packit test --identifier basic

2023-06-22 21:22 UTC, thrix commented
/packit test

2023-10-26 16:08 UTC, lukaszachy commented
@psss How about mentioning what to do with manual trigger in https://tmt.readthedocs.io/en/stable/contribute.html#pull-requests ?

2023-10-27 07:48 UTC, lachmanfrantisek commented
@psss I hope we've fixed various issues in the meantime so all should be fine now. I would just rebase the PR so the old statuses aren't preserved and we can check the fresh state (statutes can't be removed).

2023-10-27 12:23 UTC, psss commented
> @psss How about mentioning what to do with manual trigger in https://tmt.readthedocs.io/en/stable/contribute.html#pull-requests ?

Yeah, good idea!

2023-10-27 12:24 UTC, psss commented
> @psss I hope we've fixed various issues in the meantime so all should be fine now. I would just rebase the PR so the old statuses aren't preserved and we can check the fresh state (statutes can't be removed).

Yeah, I just did not get to it. Hope I'll finish this one soon.

2023-11-08 17:45 UTC, lukaszachy requested changes
Just making it clear we need manual triggers documented

2023-11-28 10:52 UTC, psss commented
/packit test --identifier basic

2023-11-28 11:12 UTC, psss commented
> Just making it clear we need manual triggers documented

The trigger comment has been documented.

2023-11-28 11:38 UTC, psss commented
Hopefully the `packit` command could be a bit shorter: packit/packit-service/issues/2259

2023-11-28 11:39 UTC, psss commented
/packit test --identifier full

2023-11-30 14:33 UTC, psss commented
/packit test --identifier full

2023-11-30 16:15 UTC, merged