Add story describing CLI for multiple phases
teemtee/tmt pull request #2286
Opened 2023-08-23 09:32 UTC by happz

A follow up for https://github.com/teemtee/tmt/pull/2188

2023-08-23 13:37 UTC, thrix requested changes
some small comments from me

2023-08-25 08:07 UTC, happz commented on stories/cli/multiple phases.fmf
> +    As a user I want to add, remove and adjust multiple phases via command line.
Tried to change in 6a031787

2023-08-25 08:08 UTC, happz commented on stories/cli/multiple phases.fmf
> +/adjust:
Fixed in 6a031787

2023-08-29 08:51 UTC, thrix approved these changes
LGTM

2023-08-29 08:55 UTC, lukaszachy approved these changes

2023-08-29 11:04 UTC, merged