Adjust imported plan to let its adjust rules make changes
teemtee/tmt pull request #2295
Opened 2023-08-29 11:54 UTC by happz

When importing a (remote) plan, its adjust rules were ignored. They may add new phases, modify environment of the plan, and should be honored and take place. Otherwise, for tests to run in the environment they expect, importing party would have to include those rules in the importing plan.

2023-08-29 11:56 UTC, thrix approved these changes
makes sense to me

2023-08-29 11:57 UTC, lukaszachy requested changes
+1 to idea and implementation but add tests please

2023-08-29 12:28 UTC, happz commented
A test added in 189fe516.

2023-08-29 12:57 UTC, lukaszachy approved these changes

2023-08-30 13:45 UTC, lukaszachy commented
@happz I believe the test showed we have another problem. IIUIC, even though `/plans/full/tmt` is 'enabled false' the `tmt run` is happy to execute it.

```
$ tmt run plan -n  /plans/full/tmt discover
/var/tmp/tmt/run-038
    
    /plans/full/tmt
        discover
            how: fmf
            directory: /var/tmp/tmt/run-038/import/plans/full/tmt
            filter: tag: virtual & tier:1
            summary: 33 tests selected
```

2023-08-30 15:01 UTC, lukaszachy approved these changes

2023-08-30 15:11 UTC, kkaarreell approved these changes

2023-08-30 15:30 UTC, merged