Move check-related code into tmt.checks
teemtee/tmt pull request #2327
Opened 2023-09-12 18:49 UTC by happz

There were some classes and functions in tmt.base that really belong into tmt.checks. The patch just moves stuff around, updating imports and type references.

2023-09-12 18:52 UTC, happz commented
@psss one for the head of the queue, if I may ask for a favor. It should be safe refactoring only, and I plan to build upon this the AVC check, i.e. easier rebases.

2023-09-13 13:48 UTC, psss requested changes
Make sense, looks nice. Let's just document the `Check.go()` method.

2023-09-13 13:48 UTC, psss commented on tmt/checks/__init__.py
> +            logger: tmt.log.Logger) -> List['CheckResult']:
Please, add a docstring.

2023-09-13 16:14 UTC, psss approved these changes

2023-09-14 09:48 UTC, merged