Record start/end time & duration of test checks
teemtee/tmt pull request #2330
Opened 2023-09-13 15:17 UTC by happz

2023-09-27 09:03 UTC, therazix approved these changes

2023-09-27 15:11 UTC, psss requested changes
Looks nice! Just two little nitpicks...

2023-09-27 15:13 UTC, psss commented
Rebased and resolved the conflict.

2023-10-02 07:11 UTC, happz commented on tmt/steps/execute/internal.py
> +                        shift=shift)
I went with this:

```
        exit-first: false
            test: /avc/harmless
                cmd: /bin/true
                00:00:00 pass /avc/harmless (on default-0) [1/1]
                00:00:00     pass avc (after-test check)
```

The "<result> <name>" block is handled by `Result.show()`, it's harder to introduce indentation into that. I want to change this but with another patch, I'm not comfortable with `Result` formatting stuff for others, and it also ignores colorization controls.

2023-10-05 10:59 UTC, psss commented on tmt/steps/execute/internal.py
> +                        shift=shift)
Yeah, makes sense.

2023-10-05 11:11 UTC, happz commented
Rebased and resolved the conflict.

2023-10-05 11:15 UTC, psss approved these changes
Thanks!

2023-10-05 12:15 UTC, merged