Change the default test pidfile directory to /var/tmp
teemtee/tmt pull request #2432
Opened 2023-10-26 07:43 UTC by happz

The original path, `/var/tmp/tmt`, may not always exist or may have unexpected permissions, preventing the pidfile from being created when less privileged account is used to access a guest.

Pull Request Checklist

* [ ] implement the feature
* [ ] write the documentation
* [ ] extend the test coverage
* [ ] update the specification
* [ ] adjust plugin docstring
* [ ] modify the json schema
* [ ] mention the version

2023-10-26 11:50 UTC, thrix approved these changes
LGTM

2023-10-26 11:50 UTC, janhavlin approved these changes

2023-10-26 13:57 UTC, psss requested changes
` /tests/execute/reboot/out-of-session` seems to be failing.

2023-10-31 09:18 UTC, psss approved these changes
Thanks! Looks good now.

2023-10-31 14:32 UTC, merged