Download all sources for dist-git-source
teemtee/tmt pull request #2438
Opened 2023-10-27 16:18 UTC by lukaszachy

Document common options on single place
Option to just download sources (no extractions)
Fix 'url' behaviour for 'shell'

Pull Request Checklist

* [ ] implement the feature
* [ ] write the documentation
* [ ] extend the test coverage
* [ ] update the specification
* [ ] adjust plugin docstring
* [ ] modify the json schema
* [ ] mention the version

2023-10-27 16:24 UTC, lukaszachy commented
I'll do changes to 'how: fmf' and tests once I know whether this is a step in the correct direction.

Example:

```
$ cat demo.fmf
discover:
  how: shell
  dist-git-source: true
  dist-git-download-only: true
  url: https://gitlab.com/redhat/centos-stream/rpms/ruby.git
execute:
  how: tmt
```

For `tmt run --id DEMO discover` one should have  all necessary files in var/tmp/tmt/DEMO/demo/discover/default-0/source to run `rpmbuild -bp`

2023-10-27 16:34 UTC, lukaszachy commented
Note to self: `TMT_SOURCE_DIR` is not available in the PREPARE steps.

2023-10-27 16:38 UTC, lukaszachy commented on spec/plans/discover.fmf
> +      ``TMT_SOURCE_DIR`` variable.
```suggestion
      ``TMT_SOURCE_DIR`` variable available in tests.
```

2023-10-30 16:17 UTC, lukaszachy commented
Q about the option name. The standard-test-role uses 'fetch_only': Should we call it the same? 

https://pagure.io/standard-test-roles/blob/master/f/roles/standard-test-source

2023-10-31 20:35 UTC, CtrlZmaster reviewed
There were a couple of places where the sentences didn't make sense to me, so I suggested changes. In other places, I felt like that the text could be interpreted incorrectly by the users, so I tried to make it more clear.

Regardless of my suggestions, this massively improved the documentation and implemented what was missing for my use case.  Thank you!

2023-11-01 11:29 UTC, lukaszachy commented on spec/plans/discover.fmf
> +            find tests defined within plans repo.
It is all just about tests. Any plans in extracted sources will not be processed. The 'current plan' which asks for the dist-git-source is already being executed (and remote plans are processed before the discovery step starts).
I'll use your suggestion as a base.

2023-11-01 11:36 UTC, lukaszachy commented on tmt/steps/discover/__init__.py
> +    dist_git_fetch_only: bool = field(
Yeah, however standard-test-roles uses fetch-only. Hard to tell what is better

2023-11-01 12:20 UTC, lukaszachy commented on spec/plans/discover.fmf
> +            find tests defined within plans repo.
How about:
```
        dist-git-merge
            Set to True to combine fmf root from the sources and fmf root from the plan.
            It allows to have tests defined in the DistGit repo which use resources
            from the extracted sources.
```

2023-11-01 12:36 UTC, lukaszachy commented on tmt/steps/discover/__init__.py
> +    dist_git_fetch_only: bool = field(
Will rename to download-only.

2023-11-01 15:16 UTC, CtrlZmaster commented on spec/plans/discover.fmf
> +            find tests defined within plans repo.
In my opinion, the comment and the suggestion are not telling the same thing, or the suggestion is being too general. The word resources is very abstract and I wouldn't really understand that it also include tests. I understood what you wrote in the first comment, so I incorporated it and I think that now it is much clearer. 

```
 dist-git-merge
             Set to True to combine fmf root from the sources and fmf root from the plan.
             It allows to have plans and tests defined in the DistGit repo which use tests and 
             other resources from the downloaded sources. Any plans in extracted sources 
             will not be processed.
```

2023-11-01 17:01 UTC, lukaszachy commented
Hopefully all comments  addressed now.  Approvals appreciated :)

2023-11-02 08:14 UTC, psss requested changes
Looks good and the wording sounds much more clear now. Proposing a couple of adjustments in 3fd2bb36 and added a few questions.

2023-11-02 09:52 UTC, lukaszachy commented on tests/discover/distgit.sh
> +if false; then
Ouch

2023-11-02 09:57 UTC, lukaszachy commented
@psss Thanks for finding those issues, fixed in [f281bb6](https://github.com/teemtee/tmt/pull/2438/commits/f281bb62f016810af1d41b5dd10b1533e0d0c4ca)

2023-11-02 09:59 UTC, psss approved these changes
Now looks good. Thanks for this nice improvement!

2023-11-02 10:36 UTC, merged