Raise an error when loading pre-1.24 tests.yaml
teemtee/tmt pull request #2573
Opened 2023-12-15 15:19 UTC by happz

`discover-phase` was added in 1.24, which is essential for correct work of `execute` in parallelized, multi-host world we inhabit these days. Emit an error and/or warning to rather than let `tmt status` crash on incompatible `tests.yaml`.

Pull Request Checklist

* [x] implement the feature
* [x] write the documentation
* [ ] extend the test coverage

2024-01-16 21:37 UTC, happz commented
> This should cover #2565, right? Shall we connect this issue? Do you still plan to add test coverage?

Added a test in fe7a75fe

2024-01-23 08:45 UTC, psss requested changes
Looks good, just one typo.

2024-01-23 08:45 UTC, psss commented on tmt/steps/discover/__init__.py
> +                # what the could could be.
A `could could` typo.

2024-01-23 08:55 UTC, happz commented on tmt/steps/discover/__init__.py
> +                # what the could could be.
Fixed in 5b9793e1

2024-01-23 09:21 UTC, psss approved these changes

2024-01-23 12:36 UTC, psss commented
/packit test -i full

2024-01-23 13:15 UTC, merged