Fail dmesg check if it contains "Call Trace"/"segfault"
teemtee/tmt pull request #2583
Opened 2023-12-23 02:07 UTC by guoguojenna

00:00:33 fail /rdma/pyverbs-tests-2 (on default-0) [1/1]
            	00:00:00 	pass dmesg (before-test check)
            	00:00:02 	pass avc (after-test check)
            	00:00:01 	**fail** dmesg (after-test check)

When users notice dmesg fail, they can go to check the dmesg output to see if it's a bug.

Fixes #2563.

Pull Request Checklist

* [x] implement the feature

2023-12-23 10:01 UTC, happz commented
@guoguojenna thanks for the patch. I for one like the idea, but I'm afraid that the check would have to be smarter to avoid spoiling all tests. Without taking timestamps into account, one segfault - even a segfault that happened right after the boot, way before tmt connected to the guest for the first time - would mark all following tests as failed. I'm afraid dmesg check would have to approach it in the way AVC check does, i.e. checking `dmesg` output since test's `start_time`, see https://github.com/teemtee/tmt/blob/main/tmt/checks/avc.py#L137C4-L137C4. I also found https://unix.stackexchange.com/questions/729243/how-to-show-dmesg-logs-within-a-certain-timeframe, but `sed` is probably not going to help as much as in that example. Maybe we could save `/proc/uptime` and check only newer lines, and avoid converting into human-readable date & time completely.

2023-12-23 10:08 UTC, happz commented on tmt/checks/dmesg.py
> +                    break
1. I'd say `ERROR_MSGS` would deserve to be a list of regular expressions, to give us more flexibility for pretty much the same price. E.g.

   ```python
   ERROR_PATTERNS = [
       re.compile(pattern)
       for pattern in [
           r'Call trace:'
           r'\ssegfault\s'
       ]
   ]
   ```

   I suspect tmt might accept these from metadata one day, and patterns can help us catch more complicated error messages. And it's just slightly more complicated and not that unreadable :)
2. and the loop above is `any` pretending it's something else :) How about this:

   ```python
   if any(pattern.search(output) for pattern in ERROR_PATTERNS):
       outcome = ResultOutcome.FAIL
   ```

   We'd use a built-in, optimized function, the intention behind the code would be more visible, and we would avoid the need for a `break`, reducing the risk of us dropping it by accident while refactoring the code next June, for example :)

2024-01-04 17:13 UTC, juk commented on tmt/checks/dmesg.py
> +                    break
This could be done similar to how restraint dmesg plugin does it [1].
* dmesg is cleared before each test execution
* dmesg is analyzed after each test execution. Any issue found by dmesg plugin is reported as test failure
* dmesg failures to lookup are configurable with:
   * Task environment variable
   * User defined file
   * defaults.

[1] https://restraint.readthedocs.io/en/latest/plugins.html#report-result

https://github.com/restraint-harness/restraint/blob/master/plugins/report_result.d/01_dmesg_check#L33

Below is an example of custom failurestring usage

https://gitlab.cee.redhat.com/kernel-qe/kernel/-/blob/master/misc/restraint-config/runtest.sh?ref_type=heads#L7

2024-01-04 20:10 UTC, happz commented
> @guoguojenna thanks for the patch. I for one like the idea, but I'm afraid that the check would have to be smarter to avoid spoiling all tests. Without taking timestamps into account, one segfault - even a segfault that happened right after the boot, way before tmt connected to the guest for the first time - would mark all following tests as failed. I'm afraid dmesg check would have to approach it in the way AVC check does, i.e. checking `dmesg` output since test's `start_time`, see https://github.com/teemtee/tmt/blob/main/tmt/checks/avc.py#L137C4-L137C4. I also found https://unix.stackexchange.com/questions/729243/how-to-show-dmesg-logs-within-a-certain-timeframe, but `sed` is probably not going to help as much as in that example. Maybe we could save `/proc/uptime` and check only newer lines, and avoid converting into human-readable date & time completely.

Actually, `dmesg -c` should clean the buffer. Running `dmesg -c > some-log.txt` before the test should empty the buffer, and running `dmesg > another-log.txt` after the test would provide the pile of text to check for issues.

2024-01-04 20:13 UTC, happz commented on tmt/checks/dmesg.py
> +                    break
> This could be done similar to how restraint dmesg plugin works [1].
> 
> * dmesg is cleared before each test execution

Yes, `dmesg -c` would empty the buffer before each test, https://github.com/teemtee/tmt/pull/2583#issuecomment-1877697192

> * dmesg is analyzed after each test execution. Any issue found by dmesg plugin is reported as test failure

That's the idea.

> * dmesg failures to lookup are configurable with:
>   
>   * Task environment variable
>   * User defined file
>   * defaults.

I'd start small. Let's have a couple of well-known patterns in the check itself to start with. Later we can add patterns into fmf data, which would also mean patterns would be acceptable via envvars. But fmf for checks is not stable yet, and having built-in list of sane defaults would give us a nice check to play with relatively quickly.

2024-01-04 20:57 UTC, juk commented on tmt/checks/dmesg.py
> +                    break
Yep, agree with having patterns as regex is a way to go.
Example of defaults:
`
Oops:.*
BUG:.*
WARNING:.*
NMI watchdog: BUG: soft lockup.*
NMI watchdog: Watchdog detected hard LOCKUP.*
Badness at.*
`
Not sure if looking up "Call trace" is a good idea. There will be some intentionally triggered by tests.

2024-01-04 21:08 UTC, happz commented on tmt/checks/dmesg.py
> +                    break
Those tests could disable the `dmesg` check. Or, later, they could overload the list of patterns and remove those about call traces.

2024-01-04 21:59 UTC, juk commented on tmt/checks/dmesg.py
> +                    break
Agree, overloading the list would do it.

2024-01-09 02:41 UTC, guoguojenna commented on tmt/checks/dmesg.py
> +                    break
> Yep, agree with having patterns as regex is a way to go. Example of defaults:
> 
>     * Oops:
> 
>     * BUG:
> 
>     * WARNING:
> 
>     * NMI watchdog: BUG: soft lockup
> 
>     * NMI watchdog: Watchdog detected hard LOCKUP
> 
>     * Badness at
> 
> 
> Not sure if looking up "Call trace" is a good idea. There will be some intentionally triggered by tests.

@juk thank you for the nice advice~

"Call trace" is generic. Most of these issues probably produce "Call trace", so looking up "Call trace" can catch most of these issues, bug or not a bug, leave it to users to check and take actions, either disable dmesg or define their applicable list of patterns in future.

So the default list can be:

 r'Call trace:',
 r'\ssegfault\s', 

Or if we feel it's a little bit aggressive, we can use this list or select some typical ones.

general protection fault:.*
BUG:.*
kernel BUG at.*
do_IRQ: stack overflow:.*
RTNL: assertion failed.*
Eeek! page_mapcount\(page\) went negative!.*
near stack overflow \(cur:.*
double fault:.*
Badness at.*
NETDEV WATCHDOG.*
WARNING: .*
appears to be on the same physical disk.*
Unable to handle kernel.*
sysctl table check failed.*
.*------------\[ cut here \]------------
list_del corruption\..*
list_add corruption\..*
NMI watchdog: BUG: soft lockup.*
irq [0-9]+: nobody cared.*
INFO: task .* blocked for more than [0-9]+ seconds.*
vmwrite error: reg .*
.*page allocation failure: order:.*
.*page allocation stalls for.*order:.*mode:
INFO: rcu_sched self-detected stall on CPU.*
INFO: rcu_sched detected stalls on CPUs/tasks:.*
NMI watchdog: Watchdog detected hard LOCKUP.*
watchdog: CPU.*
watchdog: BUG: soft lockup.*
Watchdog CPU:.* Hard LOCKUP.*
Synchronous External Abort.*
Kernel panic - not syncing: .*
Oops: Unrecoverable TM Unavailable Exception.*

https://gitlab.cee.redhat.com/kernel-qe/kernel/-/blob/master/misc/restraint-config/runtest.sh?ref_type=heads#L7

2024-01-09 02:44 UTC, guoguojenna commented on tmt/checks/dmesg.py
> +                    break
> 1. I'd say `ERROR_MSGS` would deserve to be a list of regular expressions, to give us more flexibility for pretty much the same price. E.g.
>        ```python
>        ERROR_PATTERNS = [
>            re.compile(pattern)
>            for pattern in [
>                r'Call trace:'
>                r'\ssegfault\s'
>            ]
>        ]
>        ```
>        
>        
>            
>              
>            
>        
>              
>            
>        
>            
>          
>        I suspect tmt might accept these from metadata one day, and patterns can help us catch more complicated error messages. And it's just slightly more complicated and not that unreadable :)
> 
>     2. and the loop above is `any` pretending it's something else :) How about this:
>        ```python
>        if any(pattern.search(output) for pattern in ERROR_PATTERNS):
>            outcome = ResultOutcome.FAIL
>        ```
>        
>        
>            
>              
>            
>        
>              
>            
>        
>            
>          
>        We'd use a built-in, optimized function, the intention behind the code would be more visible, and we would avoid the need for a `break`, reducing the risk of us dropping it by accident while refactoring the code next June, for example :)

Yeah, your solution is better, incorporated, thank you @happz ~

2024-01-10 02:22 UTC, guoguojenna reviewed
Ran the test again after this code change, and can fail the dmesg as expected.

```
    00:00:37 fail /rdma/pyverbs-tests-2 (on default-0) [1/2]
    00:00:01     pass dmesg (before-test check)
    00:00:02     pass avc (after-test check)
    00:00:02     fail dmesg (after-test check)
```

2024-01-10 12:08 UTC, guoguojenna commented on tmt/checks/dmesg.py
> +            invocation.guest.execute(tmt.utils.ShellScript('dmesg -C'))
Thank you, just updated again. :)

2024-01-12 20:36 UTC, juk commented on tmt/checks/dmesg.py
> +                    break
> "Call trace" is generic. Most of these issues probably produce "Call trace", so looking up "Call trace" can catch most of these issues, bug or not a bug, leave it to users to check and take actions, either disable dmesg or define their applicable list of patterns in future.
> 
> So the default list can be:
> 
> r'Call trace:', r'\ssegfault\s',
> 
> Or if we feel it's a little bit aggressive, we can use this list or select some typical ones.

Agree, let's start small and add overloading the list of patterns later

2024-01-22 12:52 UTC, thrix requested changes

2024-01-22 12:52 UTC, thrix commented on tmt/checks/dmesg.py
> +FAILURE_PATTERNS = [
An idea from me, could we have also an environment variable to extend the list of failure patterns for easier extension. If we would need to extend the list now, a new tmt version needs to happen, with the environment variable for extending the patterns the users would have a workaround.

2024-01-22 22:23 UTC, thrix commented on tmt/checks/dmesg.py
> +FAILURE_PATTERNS = [
ok, I can come back later

2024-01-23 08:50 UTC, thrix commented on tmt/checks/dmesg.py
> +                    break
closing, seems we are in agreement here.

2024-01-23 08:51 UTC, thrix commented on tmt/checks/dmesg.py
> +            invocation.guest.execute(tmt.utils.ShellScript('dmesg -C'))
closing, looks addressed

2024-01-23 08:52 UTC, thrix commented
@juk @psss @happz this seems to be ready for review

2024-01-23 09:20 UTC, lukaszachy approved these changes

2024-01-23 17:00 UTC, juk commented
> @juk @psss @happz this seems to be ready for review

Looks good to me, thank you [guoguojenna](https://github.com/guoguojenna) !

2024-01-24 14:13 UTC, psss approved these changes
Looks good, thanks for implementing this. Proposing to extend the test coverage in 35dd22c3.

2024-01-24 14:17 UTC, happz approved these changes

2024-01-24 14:23 UTC, psss commented
/packit test

2024-01-24 14:44 UTC, psss commented
/packit test -i full

2024-01-24 15:14 UTC, merged