Support terminating process running test via its test invocation
teemtee/tmt pull request #2589
Opened 2024-01-03 09:27 UTC by happz

Pull Request Checklist

* [x] implement the feature

2024-01-11 12:03 UTC, janhavlin commented on tmt/steps/execute/__init__.py
> +            invocation's test has been started by by some part of tmt code which
```suggestion
            invocation's test has been started by some part of tmt code which
```

2024-01-11 12:05 UTC, thrix requested changes
@happz a unit test would be nice, should not be hard to test?

2024-01-22 13:15 UTC, happz commented
> @happz a unit test would be nice, should not be hard to test?

Added in a36cc1c80cc117964b0b0dc470a5f6103690ea23

2024-01-22 13:16 UTC, happz commented on tmt/steps/execute/__init__.py
> +            invocation's test has been started by by some part of tmt code which
Fixed in 33bfbfb9

2024-01-22 22:20 UTC, thrix approved these changes
LGTM

2024-01-22 22:21 UTC, thrix commented
/packit test --identifier full

2024-01-23 08:25 UTC, psss approved these changes
Looks good. Thanks.

2024-01-23 08:38 UTC, psss commented
/packit test -i full

2024-01-23 09:04 UTC, psss commented
/packit test -i full

2024-01-23 10:29 UTC, psss commented
/packit test -i full

2024-01-23 10:52 UTC, psss commented
/packit test -i full

2024-01-23 11:50 UTC, psss commented
Ok, so now the `/plans/install/docs` was failing because of a real failure:

    docstring of tmt.steps.execute.TestInvocation.terminate_process:3: ERROR: Unexpected indentation.
    docstring of tmt.steps.execute.TestInvocation.terminate_process:8: WARNING: Literal block ends without a blank line; unexpected unindent.

Should be fixed by aa72ed56.

2024-01-23 12:01 UTC, psss commented
/packit test -i full

2024-01-23 12:23 UTC, merged