Have mrack support bootdisk
teemtee/tmt pull request #2668
Opened 2024-02-06 04:14 UTC by skycastlelily

Pull Request Checklist

* [ ] implement the feature
* [ ] write the documentation
* [ ] extend the test coverage
* [ ] update the specification
* [ ] adjust plugin docstring
* [ ] modify the json schema
* [ ] mention the version
* [ ] include a release note

2024-02-07 14:41 UTC, happz commented on tmt/steps/provision/mrack.py
> +class MrackHWKV(MrackHWElement):
`MrackHWKeyValue` would look better, `HWKV` is hard to grasp at quick glance.

2024-03-05 14:21 UTC, happz approved these changes

2024-03-05 16:08 UTC, psss requested changes
Thanks for implementing this. Just one nitpick. Could you please also update the release note accordingly? The checklist in the pull request description could remind about this ;-) We remove irrelevant items from it and mark as done completed items.

2024-03-05 16:08 UTC, psss commented on tmt/steps/provision/mrack.py
> +    """ An key-value element """
```suggestion
    """ A key-value element """
```

2024-03-06 01:33 UTC, skycastlelily commented
Updated:)

> The checklist in the pull request description could remind about this ;-)

Thanks for your reminder,will keep that in mind:)

On Wed, Mar 6, 2024 at 12:08 AM Petr Šplíchal ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for implementing this. Just one nitpick. Could you please also
> update the release note accordingly? The checklist in the pull request
> description could remind about this ;-) We remove irrelevant items from it
> and mark as done completed items.
> ------------------------------
>
> In tmt/steps/provision/mrack.py
> <https://github.com/teemtee/tmt/pull/2668#discussion_r1513093736>:
>
> > @@ -145,6 +146,20 @@ def __init__(self, name: str, operator: str, value: str) -> None:
>              }
>
>
> ***@***.***(init=False)
> +class MrackHWKeyValue(MrackHWElement):
> +    """ An key-value element """
>
> ⬇️ Suggested change
>
> -    """ An key-value element """
> +    """ A key-value element """
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/teemtee/tmt/pull/2668#pullrequestreview-1917471815>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKFR23DJUFPTIX726N6D26DYWXUYXAVCNFSM6AAAAABC3I3S72VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMJXGQ3TCOBRGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-08 10:01 UTC, psss approved these changes

2024-03-08 10:03 UTC, psss commented
/packit test

2024-03-08 14:09 UTC, merged