Create run.yaml for try
teemtee/tmt pull request #2889
Opened 2024-04-25 09:17 UTC by skycastlelily

Pull Request Checklist

* [ ] implement the feature
* [ ] write the documentation
* [ ] extend the test coverage
* [ ] update the specification
* [ ] adjust plugin docstring
* [ ] modify the json schema
* [ ] mention the version
* [ ] include a release note

2024-04-30 16:17 UTC, lukaszachy commented
/packit test

2024-06-11 11:35 UTC, therazix approved these changes

2024-06-11 11:56 UTC, thrix approved these changes
LGTM

2024-06-11 12:05 UTC, martinhoyer approved these changes

2024-06-12 12:06 UTC, psss requested changes
Thanks for the fix! Overall looks good. I gave it a quick try and ran into regression:

    cd
    tmt try

Before I was able to enter directory without `tmt` metadata and quickly start experimenting but now I get the following:

    No metadata found in the '.' directory. Use 'tmt init' to get started.

Could you please look into it? Also, what about extending the related test coverage a bit? We could extend the `keep` test case here:

https://github.com/teemtee/tmt/blob/cd73dd73fa4f42d709e994b6f7e20f34547c30c0/tests/try/basic/test.sh#L48-L51

It would be also good to add a test case for the above-mentioned scenario which was affected by the change.

2024-06-12 20:21 UTC, happz commented
Deferring to 1.35 to get more time to resolve the (minor yet pesky) issues reported in https://github.com/teemtee/tmt/pull/2889#pullrequestreview-2112825925

2024-06-13 09:34 UTC, skycastlelily commented
> We could extend the `keep` test case here:
> 
> https://github.com/teemtee/tmt/blob/cd73dd73fa4f42d709e994b6f7e20f34547c30c0/tests/try/basic/test.sh#L48-L51
> 
> It would be also good to add a test case for the above-mentioned scenario which was affected by the change.

Looks like keep test case also covers that scenario

```
(dev) lnie@fedora:~/tmt$ cat ./tests/try/basic/data/keep.exp
#!/usr/bin/expect -f
# Select a plan and keep the run

spawn tmt try -p plan
expect "What do we do next?"
send -- "k\r"
expect eof
```

I can reproduce that issue with my original MR but can't produce it after updated the code 

```
[lnie@ceph-04 ~]$ tmt try -p plan
/var/tmp/tmt/run-009
No metadata found in the '.' directory. Use 'tmt init' to get started.

[lnie@ceph-04 ~]$ tmt try -p plan
/var/tmp/tmt/run-010
No plan matching 'plan' found.
```
Please let me know if I miss anything,thanks:)

2024-07-08 19:19 UTC, therazix commented
@skycastlelily It looks like commit 421fea8b7716586bfe495ca9307a94c8becf6af4 doesn't belong to this pull request and shouldn't be here.

2024-07-10 03:52 UTC, skycastlelily commented
Not sure how it happened😅 Should be good now:)

On Tue, Jul 9, 2024 at 3:19 AM Filip Vágner ***@***.***>
wrote:

> @skycastlelily <https://github.com/skycastlelily> It looks like commit
> 421fea8
> <https://github.com/teemtee/tmt/commit/421fea8b7716586bfe495ca9307a94c8becf6af4>
> doesn't belong to this pull request and shouldn't be here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/teemtee/tmt/pull/2889#issuecomment-2214994217>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKFR23CRES2IKAH4YE2G6M3ZLLQ5JAVCNFSM6AAAAABGYPEWPWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMJUHE4TIMRRG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-31 11:08 UTC, happz commented
@skycastlelily would you be able to add a test as suggested by Petr in https://github.com/teemtee/tmt/pull/2889#pullrequestreview-2112825925? Even a trivial one would be better than nothing.

2024-07-31 11:13 UTC, thrix commented
> @skycastlelily would you be able to add a test as suggested by Petr in [#2889 (review)](https://github.com/teemtee/tmt/pull/2889#pullrequestreview-2112825925)? Even a trivial one would be better than nothing.

I believe she covered this in this reply https://github.com/teemtee/tmt/pull/2889#issuecomment-2165131328

2024-07-31 11:28 UTC, happz commented
/packit test

2024-07-31 13:03 UTC, happz commented
Unrelated failures, merging.

2024-07-31 13:04 UTC, merged