Update spec files
teemtee/tmt pull request #3066
Opened 2024-07-02 00:46 UTC by skycastlelily

Pull Request Checklist

* [ ] implement the feature
* [ ] write the documentation
* [ ] extend the test coverage
* [ ] update the specification
* [ ] adjust plugin docstring
* [ ] modify the json schema
* [ ] mention the version
* [ ] include a release note

2024-07-02 07:07 UTC, happz commented
@skycastlelily please, consider extending the subject. "Update spec files" can mean anything, and provides no pointer to what changed and why. Something like "Update HW requirement implementation links to match reality" would be way more helpful.

2024-07-02 14:43 UTC, skycastlelily commented
Updated^^

On Tue, Jul 2, 2024 at 3:07 PM Miloš Prchlík ***@***.***>
wrote:

> @skycastlelily <https://github.com/skycastlelily> please, consider
> extending the subject. "Update spec files" can mean anything, and provides
> no pointer to what changed and why. Something like "Update HW requirement
> implementation links to match reality" would be way more helpful.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/teemtee/tmt/pull/3066#issuecomment-2202120975>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKFR23HMRG33AO5FM6AJM3LZKJGTPAVCNFSM6AAAAABKGQL7V6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMBSGEZDAOJXGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-16 11:45 UTC, therazix requested changes

2024-07-16 11:45 UTC, therazix commented on spec/hardware/disk.fmf
> +    note: "``size`` ``model-name`` only"
```suggestion
    note: "``size`` and ``model-name`` only"
```

2024-07-16 12:02 UTC, thrix commented
> Updated^^

@skycastlelily thx, I updated also MR description :) unfortunately it is not done automatically :(

2024-07-17 01:38 UTC, skycastlelily commented on spec/hardware/disk.fmf
> +    note: "``size`` ``model-name`` only"
Updated:)

2024-07-17 01:38 UTC, skycastlelily commented
> > Updated^^
> 
> @skycastlelily thx, I updated also MR description :) unfortunately it is not done automatically :(

Thanks:)

2024-07-18 11:42 UTC, thrix approved these changes
LGTM

2024-07-18 11:51 UTC, therazix approved these changes

2024-07-18 13:07 UTC, psss commented
Specification update --> full test not needed --> merging.

2024-07-18 13:07 UTC, merged