Fix a bug when prune is used along with path
teemtee/tmt pull request #3132
Opened 2024-08-06 09:35 UTC by KwisatzHaderach

There was a bug found when test pruning is used along with path argument in discover

Fixes #3131 

Pull Request Checklist

* [x] implement the feature
* [ ] extend the test coverage
* [ ] include a release note

2024-08-06 13:04 UTC, psss requested changes
This fix looks good and I was able to reproduce and verify the issue with the original repository. But the test does not reproduce the problem. It might be related to the use of relative `path` in the plan.

2024-08-06 13:36 UTC, KwisatzHaderach commented on tests/discover/prune.sh
> +        rlAssertNotExists "$run/nested/discover/default-0/tests/test2"
right, works fine with teemtee/tests, even found another issue with .fmf matching

2024-08-06 14:15 UTC, psss commented on tests/discover/prune/nested.fmf
> +    path: nested
With `url` it's now according to the spec ;-)

2024-08-06 14:17 UTC, psss approved these changes
Now looks good. Thanks for fixing this!

2024-08-06 17:57 UTC, happz approved these changes

2024-08-07 08:04 UTC, psss commented
The `provision` plan failure is irrelevant:

    Couldn't fetch Fedora releases from oraculum...

Merging.

2024-08-07 08:04 UTC, merged