Store the original test outcome in results
teemtee/tmt pull request #3147
Opened 2024-08-14 07:56 UTC by happz

Pull Request Checklist

* [x] implement the feature
* [x] write the documentation
* [ ] extend the test coverage
* [x] update the specification
* [ ] mention the version
* [ ] include a release note

2024-09-10 11:57 UTC, KwisatzHaderach approved these changes

2024-09-17 12:00 UTC, therazix approved these changes

2024-09-24 12:44 UTC, seberm approved these changes

2024-09-25 14:26 UTC, happz commented
/packit test

2024-09-26 11:52 UTC, martinhoyer approved these changes
I wish I saw this before working on it in https://github.com/teemtee/tmt/pull/3239 lol

2024-09-30 17:27 UTC, martinhoyer commented
btw, in results.py 
```
        # Extend existing note or set a new one
        if self.note:
            self.note += f', original result: {self.result.value}'
        elif self.note is None:
            self.note = f'original result: {self.result.value}'
```
shouldn't it be `self.original_result.value`?

2024-09-30 17:39 UTC, happz commented
> btw, in results.py
> 
> ```
>         # Extend existing note or set a new one
>         if self.note:
>             self.note += f', original result: {self.result.value}'
>         elif self.note is None:
>             self.note = f'original result: {self.result.value}'
> ```
> 
> shouldn't it be `self.original_result.value`?

At this moment, `self.result` and `self.original_result` should be the same value, I'm looking at code and `self.result` is modified a few lines later.

2024-09-30 20:41 UTC, psss requested changes

2024-09-30 20:53 UTC, happz commented on tmt/schemas/results.yaml
> +      original_result:
Correct, fixed in 2ca36d83

2024-09-30 21:03 UTC, psss approved these changes
Looks good, thanks!

2024-10-01 07:23 UTC, psss commented
Red tests are irrelevant failures, merging.

2024-10-01 07:23 UTC, merged