Add `dev` plans
teemtee/tmt pull request #3157
Opened 2024-08-20 14:03 UTC by LecrisUT

The idea here to add tmt plans that run without a `copr_build` as if it was run in a GH action environment. Candidates for tests that can be included here:
- `tmt-lint`: See #3117 for failed attempts at integrating the current repo in `pre-commit`
- `docs` tests from GH workflows. Blocked by ability to keep git metadata
- `mypy`/`pyright` (with development packages)
- `/plans/install/pip`

---

Pull Request Checklist

* [x] implement the feature

2024-08-20 14:42 UTC, LecrisUT commented
Oh, `/plans/sanity` is a duplicate. Quite annoying to reduce it though since it is used in other places as well :thinking:

2025-09-04 11:05 UTC, LecrisUT commented on plans/sanity/main.fmf
> +        source /tmp/venv/bin/activate
Known limitation will revisit after https://github.com/teemtee/tmt/issues/3981

2025-09-04 19:34 UTC, happz commented on tests/dev/pip/install.fmf
> +    SETUPTOOLS_SCM_PRETEND_VERSION_FOR_TMT: 0.0.1.dev0
Hell no. So many responses wasted on a single issue.

2025-09-08 14:54 UTC, LecrisUT commented on tests/dev/pip/install.fmf
> +    SETUPTOOLS_SCM_PRETEND_VERSION_FOR_TMT: 0.0.1.dev0
Seriously this thing refuses to learn. FTR both variants are acceptable, but I have no idea why this is failing, maybe the check is done much later

2025-09-09 11:02 UTC, LecrisUT commented
So the only changes I've made were with aa36438 and 5156379 and the pip install worked, but now the `tmt-lint` one is failing on the same issue even though it is the same thing. The only other difference I see is the pip upgrade but that one I've tried locally as well

2025-09-10 06:01 UTC, happz commented on .packit.yaml
> +  # CI tests (independent of OS)
Other checks are also CI tests - not OS agnostic, but still CI. Maybe something along the lines of "OS-agnostic tests, running directly in Github actions"?

2025-09-10 06:01 UTC, happz commented on tests/dev/tmt-lint/main.fmf
> +tag+: [ with_tmt ]
We definitely prefer `-` as a separator in tag names.

2025-09-10 06:01 UTC, happz commented on plans/dev/main.fmf
> +/with_tmt:
I believe we prefer `-` as a multiword separator.

2025-09-10 06:01 UTC, happz commented on plans/dev/main.fmf
> +  filter: "tag: dev"
My main issue: "dev" is very ambiguous. It can mean a lot of things, and by seeing "dev" plans, it's really not clear what to expect. Any tips for a name better reflecting the purpose of the plan?

2025-09-10 08:17 UTC, LecrisUT commented on plans/dev/main.fmf
> +  filter: "tag: dev"
Open to suggestions since I can't come up with another one. The idea of `dev` is to mirror the optional dependencies (or rather dependency-group) of `dev`, which are typically meaningful for upstream development only, and typically do not require the installation of the project itself, typically `pre-commit`, `ruff`, etc.

2025-09-10 08:27 UTC, LecrisUT commented on .packit.yaml
> +  # CI tests (independent of OS)
Hmm yeah. Trying to find a better comment there
```
Development checks (independent of OS)
```
Or
```
OS-agnostic checks
```
They are not really tests, they are more like linters, coding-standards, etc.

2025-09-10 08:29 UTC, happz commented on .packit.yaml
> +  # CI tests (independent of OS)
Sure, no need to keep "tests" in. "OS-agnostic checks" LGTM.

2025-09-10 13:17 UTC, happz commented
Bumped from 1.57, will be reviewed on the planning meeting.

2025-09-15 16:11 UTC, psss requested changes
Added a couple comments.

2025-09-15 16:11 UTC, psss commented on plans/dev/pip.fmf
> +        test: /tests/dev/pip/install/full
So these seems to be, for now, duplicating:

* `/plans/install/pip/full`
* `/plans/install/pip/mini`

But would be dropped once we see the new approach is stable?

2025-09-15 16:11 UTC, psss commented on plans/dev/main.fmf
> +execute:
Let's include a short summary to make it clear what these plans are about?

2025-09-15 16:11 UTC, psss commented on plans/dev/main.fmf
> +  filter: "tag: dev"
Hmmm, what about something like `sanity`? Or `source`? Meaning we are running tests against the project source files, not packages?

2025-09-15 16:11 UTC, psss commented on plans/dev/main.fmf
> +/with-tmt:
The name does not say much. If we go with `source`, this one could perhaps be `/plans/source/sanity`?

2025-09-15 16:13 UTC, LecrisUT commented on plans/dev/pip.fmf
> +        test: /tests/dev/pip/install/full
Yes, more specifically, once we generalize this to run for all available python versions.

2025-09-17 08:52 UTC, LecrisUT commented on plans/dev/main.fmf
> +execute:
That's a branch so it wouldn't be executed, but good point, I'm making `/plans/dev/without-tmt` to make place for that.

2025-09-17 09:54 UTC, LecrisUT commented on plans/dev/main.fmf
> +/with-tmt:
Yeah, the naming is tricky. I would want to keep the `with`/`without` tmt suffixes, because those should be the only distinction between the tests run there. Maybe `/plans/sanity` has the closest naming, but that onle still misses the fact that these are distro-agnostic plans.

2025-09-23 13:18 UTC, LecrisUT commented on plans/sanity/pip.fmf
> +    script: python3 -m venv /tmp/venv && /tmp/venv/bin/pip install --upgrade pip
Not a requirement, and this part will be refactored in a future change

2025-09-23 13:19 UTC, LecrisUT commented
Renamed to sanity plans (merged with existing one) and updated the description

2025-09-23 19:14 UTC, psss commented
Tests are failing becase the removed plan `/plans/sanity/lint` is used for testing remote plan import:

https://github.com/teemtee/tmt/blob/1e200d6832dfc21069d0bbe3b7fae68d0c4de3cd/tests/plan/import/data/plans.fmf#L4-L6

Let's choose some other plan, or create a simple one in the https://github.com/teemtee/tests/ repository.

2025-09-23 19:30 UTC, LecrisUT commented
> Tests are failing becase the removed plan `/plans/sanity/lint` is used for testing remote plan import:
> 
> https://github.com/teemtee/tmt/blob/1e200d6832dfc21069d0bbe3b7fae68d0c4de3cd/tests/plan/import/data/plans.fmf#L4-L6
> 
> Let's choose some other plan, or create a simple one in the https://github.com/teemtee/tests/ repository.

Guess my IDE didn't catch all occurrences. I've used `/plans/sanity/with-tmt` there. But if we can decouple it, that would be much preferred instead

2025-09-23 20:13 UTC, psss commented
> But if we can decouple it, that would be much preferred instead

What about something like this?

 * https://github.com/teemtee/tests/pull/15

2025-09-24 05:28 UTC, psss commented
Ok, merged the tests pull request. Let's update the references here.

2025-09-24 08:10 UTC, LecrisUT commented on tests/plan/import/basic.sh
> +        # rlAssertGrep "\<import\>" $rlRun_LOG
Had to disable these checks because it clashes with the `import` word in the description. Once those are removed, this can be reverted.

2025-09-24 09:18 UTC, psss commented on tests/plan/import/local-and-remote/main.fmf
> +    name: /plans
```suggestion
    name: /plans/remote
```

I guess, this should point to a single plan as before?

2025-09-24 09:26 UTC, LecrisUT commented on tests/plan/import/local-and-remote/main.fmf
> +    name: /plans
Yep, read the test wrong on that one.

2025-09-24 09:49 UTC, psss commented on plans/sanity/pip.fmf
> +    script: python3 -m venv /tmp/venv && /tmp/venv/bin/pip install --upgrade pip
This one actually sounds reasonable.

2025-09-24 09:54 UTC, psss commented on tests/plan/import/basic.sh
> +        # rlAssertGrep "\<import\>" $rlRun_LOG
Yeah, makes sense for now.

2025-09-24 09:54 UTC, LecrisUT commented on plans/sanity/pip.fmf
> +    script: python3 -m venv /tmp/venv && /tmp/venv/bin/pip install --upgrade pip
An issue for a later refactor. It's existing from the previous plans design, but will be moved entirely in the tests. Part of

> - Keeping the pre-commit tmt lint and /plans/install/pip for now, but will be removed in a later change

2025-09-24 09:58 UTC, psss commented on plans/sanity/pip.fmf
> +    script: python3 -m venv /tmp/venv && /tmp/venv/bin/pip install --upgrade pip
Ack.

2025-09-24 09:59 UTC, psss approved these changes

2025-09-24 11:03 UTC, LecrisUT commented
The test failure seems rather random, but specifying a provision should fix it: https://github.com/teemtee/tests/pull/18

2025-09-24 12:14 UTC, psss commented
Missing approval, not tied with the release, postponing.

2025-09-25 16:37 UTC, LecrisUT commented
For some reason @thrix approval is in a supersposition. It is approved in the "PR checks" but awaiting review in the "Reviewers"

2025-10-06 10:34 UTC, thrix approved these changes
LGTM, nothing found to comment on

2025-10-08 14:16 UTC, thrix commented
the test failure seems to be a flake, slow openstack machine

2025-10-08 14:29 UTC, merged