Add support for subresults (experimental flavor) to junit report plugin
teemtee/tmt pull request #3177
Opened 2024-08-28 21:27 UTC by seberm

This PR adds a `subresults` junit report plugin flavor to show the `tmt.result.SubResult` instances within the `tmt.Result`. It tries to map the `tmt.Result` to `<testsuite>` and `tmt.result.SubResult` to `<testcase>` respectively.

For more info see:
- https://github.com/teemtee/tmt/issues/2826#issuecomment-2077125937

Related to:
- https://github.com/teemtee/tmt/pull/3150
- https://github.com/teemtee/tmt/issues/2826

# TODO:
- [ ] Test with https://github.com/teemtee/tmt/pull/3166
- [ ] Add tests to cover the subresults

Pull Request Checklist

* [ ] implement the feature
* [ ] write the documentation
* [ ] extend the test coverage
* [ ] update the specification
* [ ] adjust plugin docstring
* [ ] modify the json schema
* [ ] mention the version
* [ ] include a release note

2024-09-03 17:47 UTC, seberm commented
@kkaarreell Hello,
I am studying various formats of JUnit. In this PR, I created a new `subresults` JUnit flavor with nested `<testsuite>` elements. Unfortunately, it seems that the `<testsuite>` elements cannot contain the same elements as `<testcase>` - especially tags like `<error>`, `<failure>`, and `<skipped>`. At least according to these specs/examples:
- https://github.com/testmoapp/junitxml/blob/main/examples/junit-complete.xml
- https://github.com/junit-team/junit5/blob/main/platform-tests/src/test/resources/jenkins-junit.xsd

This basically means if there are `failed`/`skipped`/... tests that do not contain any subresults, we will be unable to export their result. This probably means that all the `<testsuite>` elements should contain `<testcase>` elements and we must somehow create a test hierarchy using `class` attributes.

The example of the currently generated JUnit `subresults` flavor:

```
<?xml version='1.0' encoding='utf-8'?>
<testsuites disabled="0" errors="0" failures="1" tests="3" time="0">
  <testsuite name="/tests/call-dmesg" disabled="0" errors="0" failures="0" skipped="0" tests="0" time="0" timestamp="2024-08-13T12:00:22.022008+00:00">
  </testsuite>
  <testsuite name="/tests/mine-rep-multi" disabled="0" errors="1" failures="1" skipped="0" tests="3" time="0" timestamp="2024-08-13T12:00:22.881823+00:00">
    <testcase name="/tests/mine-rep-multi/test/good">
    </testcase>
    <testcase name="/tests/mine-rep-multi/test/fail">
      <failure type="failure" message="fail"/>
    </testcase>
    <testcase name="/tests/mine-rep-multi/test/weird">
      <error type="error" message="warn"/>
    </testcase>
  </testsuite>
  <testsuite name="/tests/mine-rep-pass" disabled="0" errors="0" failures="0" skipped="0" tests="0" time="0" timestamp="2024-08-13T12:00:23.752135+00:00">
  </testsuite>
</testsuites>
```

Any hints / ideas?

2024-09-04 10:59 UTC, kkaarreell commented
Hi @seberm ,
I think we have been discussing this topic in one of the mtgs.  You are right that jUnit doesn't allow nested testsuites and therefore jUnit won't be able to implement this feature. There was a proposal to identify which parts of the pipeline (which apps, scripts etc.) would be using this "per-phase" reporting and based on this findings implement changes in tmt. Maybe we would end up producing brand new output file for this.

2024-09-09 15:48 UTC, seberm commented
> Maybe we could always include at least one testcase, representing the test itself?

Yeah, I had the same idea - I did the modifications. The output is now:

```
<?xml version='1.0' encoding='utf-8'?>
<testsuites disabled="0" errors="0" failures="1" tests="3" time="0">
  <testsuite name="/tests/call-dmesg" disabled="0" errors="0" failures="0" skipped="0" tests="0" time="0" timestamp="2024-08-13T12:00:22.022008+00:00">
      <testcase name="/tests/call-dmesg">
      </testcase>
  </testsuite>

  <testsuite name="/tests/mine-rep-multi" disabled="0" errors="1" failures="1" skipped="0" tests="3" time="0" timestamp="2024-08-13T12:00:22.881823+00:00">
    <testcase name="/tests/mine-rep-multi">
      <failure type="failure" message="fail"/>
    </testcase>
    <testcase name="/tests/mine-rep-multi/test/good">
    </testcase>
    <testcase name="/tests/mine-rep-multi/test/fail">
      <failure type="failure" message="fail"/>
    </testcase>
    <testcase name="/tests/mine-rep-multi/test/weird">
      <error type="error" message="warn"/>
    </testcase>
  </testsuite>

  <testsuite name="/tests/mine-rep-pass" disabled="0" errors="0" failures="0" skipped="0" tests="0" time="0" timestamp="2024-08-13T12:00:23.752135+00:00">
    <testcase name="/tests/mine-rep-pass">
    </testcase>
  </testsuite>
</testsuites>
```

And now we need to test against the various systems/scripts which would be using this flavor. E.g. ReportPortal.

2024-09-09 16:10 UTC, kkaarreell commented
I am sorry but this seems like introducing yet another jUnit format. What tools are expected to work such a XML file? Why not introducing new report plugin for it?

2024-10-14 10:55 UTC, seberm commented
@psss @happz 

Let's separate this PR into two parts:

1. **Functional part** (most of the changes in `junit.py` file) - Without it, the users cannot *fully* experiment with subresults even with the `custom` template/flavor because the subresults are not wrapped into the `ResultsContext` (which means the subresult statistics/properties are not available).
2. **The actual subresults flavor support** (`subresults` flavor, XSD schema, subresults XML template, ...) - The final format of the JUnit file with subresults supported by tmt (and probably TestingFarm) in the future. This part still needs discussion and user feedback. We still don't know how/where the users want to use it and what is the expected format.

Any ideas? Should I prepare the PR for **(1)**? And I would keep the changes for **(2)** as part of this PR.

2024-10-16 08:00 UTC, happz commented
Splitting work into multiple PRs makes sense to me.

2024-10-22 10:38 UTC, seberm commented
/packit build

2024-10-22 10:38 UTC, seberm commented
/packit test

2024-12-05 14:00 UTC, seberm commented on tmt/steps/report/junit/templates/subresults.xml.j2
> +            {% set main_log = result.log | first | read_log %}
The logs must not be saved into the memory/variable. It must be handled same way as in: https://github.com/teemtee/tmt/pull/3382

2025-03-06 11:16 UTC, psss commented
This one is blocking finishing the focus issue, adding to the backlog with the `must` priority.

2025-03-27 07:58 UTC, psss commented
Thanks for the updates. There seems to be just one remaining [failure](https://artifacts.dev.testing-farm.io/2a2b8af6-3c09-4dcf-9643-2c0c72a996e5/work-the-restyjh85m93/plans/features/steps/the-rest/execute/data/guest/default-0/tests/report/junit-7/output.txt):

    :: [ 14:24:38 ] :: [   FAIL   ] :: File 'subresults-out.xml' should contain '<testsuite name="/test/beakerlib/subresults" disabled="0" errors="1" failures="3" skipped="2" tests="10"'

2025-03-27 19:54 UTC, happz commented on docs/releases.rst
> +``<testcase>`` tags for each ``tmt.result.SubResult``.
For a user, `tmt.Result` and `tmt.result.Subresult` will not be very useful. How about "..., test results become represented with ``<testsuite>`` tags  with one ... for each subresult."?

2025-03-27 19:54 UTC, happz approved these changes

2025-03-28 10:13 UTC, seberm commented on docs/releases.rst
> +``<testcase>`` tags for each ``tmt.result.SubResult``.
Hello @happz, fixed and improved. Thanks!

2025-04-01 11:55 UTC, thrix requested changes

2025-04-01 11:56 UTC, thrix commented on tests/report/junit/test.sh
> +            rlRun "tmt run -avr execute -h $method report -h junit --file subresults-out.xml --flavor subresults 2>&1 >/dev/null | tee output" 2
Never mind, it is part of the code itself :)

2025-04-01 11:59 UTC, psss approved these changes
Thanks much for implementing this! Looks good and works as expected. Just updated the release note in c9df51b7. Should now be ready for merge.

2025-04-01 13:56 UTC, merged