Move dataclass to dedicated module
teemtee/tmt pull request #3195
Opened 2024-09-05 16:18 UTC by LecrisUT

A few reasons for this move:
- It would make migrating to `attrs` more easy #2831
- Plugin developers should use the same dataclass type
- This would allow some neat customization, e.g. if we add https://github.com/rr-/docstring_parser, we can move the `help` to the attribute's docsting

A few things to point out:
- All `dataclass` and `field` usage are now unified and populate the `metadata`. In principle this should be fine since it would just populate a field that would never be used, but should we do something else there to distinguish between `DataContainer` type of dataclasses and plain `dataclass` like the ones in `hardware.py`?
- The import syntax is a bit disjoint. The naming of `dataclasses` and the `from import` is done like this in order to minimize the diffs for the purpose of initial review, but I think we should change it to be more uniform w.r.t. full name `tmt.dataclasses.dataclass` vs short name `field`

---

Pull Request Checklist

* [x] implement the feature
* [ ] write the documentation

2024-09-05 17:00 UTC, LecrisUT commented
What do you think about putting these into a package `tmt.containers` and moving the remaining implementations there as well.

2024-09-05 17:23 UTC, martinhoyer reviewed
My word should have very little weight here, but fwiw I like it.  To me it makes things a bit more 'digestable'.  

I wonder if we shouldn't come up with a master plan for what do we want in what file, subpackage, etc, so there is a clear logic and goal to stive for.

As for attrs, can't comment at the moment, but am educating myself about attrs vs dataclasses usage.

2024-09-05 19:42 UTC, happz commented
> What do you think about putting these into a package `tmt.containers`...

+1 to `tmt.containers`. I have it somewhere in my stash, I tried something similar: move basic classes and functions and helpers like `field()` or `container_*` out of `tmt.utils`. It'd be aligned with the goal of separating code from the implementation detail like the dataclasses (or `attrs`, when the time comes).

> ... and moving the remaining implementations there as well.

Which implementations? If you mean `SerializableContainer` and other "data container" classes, then yep, I'd like to do that as well. My idea was to have all these helpers and classes in their own module, both to simplify `tmt.utils` and keep the rest of the code clean.

2024-09-06 09:28 UTC, LecrisUT commented
Cool, I've moved the stuff around, I think after this the only things left to move would be `Common` and the Exceptions? Otherwise everything else would still be under `utils` but split into more manageable files.

I think it would also be good to start using `__future__.annotations` and `.pyi` files, it's so easy to hit circular dependencies on these.

Next step for this would be to detangle the some of these dataclasses and revert some of the redirects. In some cases it is obvious like `tmt.utils.CommandOutput` should be vanilla `dataclass`, and everything inheriting `container` should be the redirected, but then there are some grey ones like `tmt.hardware.ConstraintComponents` which are a bit in between those. Any thoughts on renaming `dataclass` to something distinct from vanilla `dataclass`/`attrs.define`? What about `tmt_data`/`fmf_data`, and maybe similarly `tmt_field`/`fmf_field`?

2024-09-06 10:11 UTC, martinhoyer commented
> I think it would also be good to start using __future__.annotations

+1

2024-09-06 14:15 UTC, happz commented
> Cool, I've moved the stuff around, I think after this the only things left to move would be `Common` and the Exceptions? Otherwise everything else would still be under `utils` but split into more manageable files.

Exceptions were on my list for sure, something like `tmt.exceptions` (or `_exceptions`). I was fine with `Common` staying where it was, maybe being moved into some `tmt.utils` submodule.

> I think it would also be good to start using `__future__.annotations` and `.pyi` files, it's so easy to hit circular dependencies on these.

`__future__.annotations` sounds good, I'm much less fond of stub files, it always felt detached from the code & two places that need to be updated when changing signatures.

> Next step for this would be to detangle the some of these dataclasses and revert some of the redirects. In some cases it is obvious like `tmt.utils.CommandOutput` should be vanilla `dataclass`

It already is, isn't it?

> and everything inheriting `container` should be the redirected, but then there are some grey ones like `tmt.hardware.ConstraintComponents` which are a bit in between those. Any thoughts on renaming `dataclass` to something distinct from vanilla `dataclass`/`attrs.define`? What about `tmt_data`/`fmf_data`, and maybe similarly `tmt_field`/`fmf_field`?

Hmm, none of the options looks tempting, sorry. Why do you want to rename them? That might help us spend a couple of productive weeks, selecting the right name :)

2024-09-06 16:54 UTC, LecrisUT commented
> `__future__.annotations` sounds good, I'm much less fond of stub files, it always felt detached from the code & two places that need to be updated when changing signatures.

I was thinking stub files as additive to keep things cleaner from parts like `@overload`, but indeed I can see it can easily get out-of-sync. There is one situation where it might be necessary, and that is for `@deprecated` because we cannot decorate an attribute.

> > Next step for this would be to detangle the some of these dataclasses and revert some of the redirects. In some cases it is obvious like `tmt.utils.CommandOutput` should be vanilla `dataclass`
> 
> It already is, isn't it?
> 
> > and everything inheriting `container` should be the redirected, but then there are some grey ones like `tmt.hardware.ConstraintComponents` which are a bit in between those. Any thoughts on renaming `dataclass` to something distinct from vanilla `dataclass`/`attrs.define`? What about `tmt_data`/`fmf_data`, and maybe similarly `tmt_field`/`fmf_field`?
> 
> Hmm, none of the options looks tempting, sorry. Why do you want to rename them? That might help us spend a couple of productive weeks, selecting the right name :)

The idea here is that we can do a few more optimizations if we know that the `dataclass` is associated with a `container`/`fmf` object:
- unify the attribute docstring and click help, which can help quite a bit for navigating the code with the IDEs
- unify the `fmf` spec documentation with the python code (or if we are bold we could even generate/append the python docstring from the fmf files, but not sure if IDEs would render it)
- generate json schema from the annotations
- generally most other features could be handled by inheritance and `__init_subclass__`, but maybe some parts are easier done by overriding the `dataclass` instead, annotations stuff being one of them that I know of

But another main reason is for plugin developers to guarantee that any improvements made on the base tmt containers do not require any refactoring on their side.

2024-09-09 10:02 UTC, LecrisUT commented
> > I was thinking stub files as additive to keep things cleaner from parts like `@overload`, but indeed I can see it can easily get out-of-sync. There is one situation where it might be necessary, and that is for `@deprecated` because we cannot decorate an attribute.
> 
> Hm, I could live with the current approach, something like `field(..., deprecated=...)`.

I am thinking of something slightly different. For `field` deprecation I think that's the only way we can do it currently until decorators can be attached to attributes and annotations, which I don't really know how that would work. What I was thinking of deprecating via stub files is if a plugin has:
```
from tmt.utils import field
```
which would deprecate to point the developer to `tmt.dataclasses.field` instead. For most cases we can create a shim, but if we want to deprecate a constant/variable, that is significantly more challenging. We can do it with the stub files though because we can simply lie about its type in there.

> > * unify the `fmf` spec documentation with the python code (or if we are bold we could even generate/append the python docstring from the fmf files, but not sure if IDEs would render it)
> 
> WDYT about code being the source here? My idea was to make plugin code the single source of truth, and generate plugin documentation, schema, and everything from the code of the plugin. The same would apply to spec like test/plan/story fields.

:+1: to that. Would work similar with the json schema generation.

> > * generate json schema from the annotations
> 
> Yep, that's one of the goals :)

[Here](https://github.com/scikit-build/scikit-build-core/blob/main/src/scikit_build_core/settings/skbuild_schema.py) is some reference form `scikit-build-core`. I think we can simplify it a lot with jinja templating.

> > * generally most other features could be handled by inheritance and `__init_subclass__`, but maybe some parts are easier done by overriding the `dataclass` instead, annotations stuff being one of them that I know of
> > 
> > But another main reason is for plugin developers to guarantee that any improvements made on the base tmt containers do not require any refactoring on their side.
> 
> I think we are aligned, at least in general, and what remains are the technicalities. For example, this move of "base container classes" into other own location, absolutely. What I'm less sure is whether we speak the same language when it comes to names, e.g.
> 
> > Any thoughts on renaming dataclass to something distinct from vanilla dataclass/attrs.define? What about tmt_data/fmf_data, and maybe similarly tmt_field/fmf_field?
> 
> If you mean the original `dataclasses.dataclass` decorator, and you think we should use it in tmt code instead of "raw" `@dataclasses.dataclass`, then yes, I think that makes sense - for me, the benefit would be we could change the implementation of `tmt.container.whateverdecorator` without polluting diff with oneliners changing what decorator is used in all plugins and base. So this makes sense from this PoV.

Indeed we are in sync on this thought :+1:.

> Just a couple of notes:
> 
>     * I would really like to avoid "data". I don't like "step data", I think "data" as a term is very vague, it can mean anything, depending on context, it's hard to speak about without ambiguity, and so on. I liked "container" because it seems less "data"-ish than `dataclass` and still represents what the class is used for, a container for, well, data. Fields. That's why I added various `container_*` helpers, so I for one would do something like `from dataclasses import dataclass as container`.

Hmm, makes sense. One alternative is `attrs` syntax of `define`, wdyt? I like the looks of `tmt.containers.define` much better than `dataclass`'s snytax.

>     * I like "field", it seems to be an acceptable term to both dataclasses and attrs, and it fits the namespace in my head. We have our custom implementation, once everything does `from tmt.containers import field`, do we even need to call it `tmt_field`/`fmf_field`? I'm not sure I understand the need for a distinct name here.

This can be relaxed. It's mostly from navigating the `tmt` code and finding `field()` and it is not clear if it's `dataclasses.field` or `tmt.utils.field`. That of course can be fixed with `ruff` to request qualified names, and maybe we can ship some recommended `ruff` settings for plugin developing.

>     * I'm not 100% sure we would be able to perform the transition as painlessly as I mentioned above, i.e. without polluting plugins with trivial import changes; given how entangled everything is internal, getting things perfect enough that we would just swap one implementation for another without plugins noticing is a very tall order - we may end up with some `field_new` or field_v2` temporarily, and I for one would be fine with that, as long as there is a good reason and a plan how to resolve it, in the next release, for example. We have some breathing space, although it would be fine to not regress in functionality too much, too often and for too long :)

You mean w.r.t. review or with functionality? And I guess this is for the `tmt` code only, or maybe there are some other `tmt` plugins that I should keep in mind to preserve compatibility. If it's the former, then shouldn't it be resolved by splitting the PR into more minimal commits?

>     * I'd very much argue in favor of multiple PRs. While it's possible to put multiple nice commits into one PR, when the merge time comes, it's harder to squash what should be squashed, and preserve history. Also the review seems to work better when it's less changes in one PR, at least when a potential reviewer checks the PR for the first time - seeing 50 changed files may discourage even the bravest ones, despite the changes being put in nice & tidy commits.

:+1: I can work with that. Let's finish the design discussion in this PR, and then I'll open a few separate PRs by cherry-picking form here.

2024-09-25 19:56 UTC, happz commented
> > > I was thinking stub files as additive to keep things cleaner from parts like `@overload`, but indeed I can see it can easily get out-of-sync. There is one situation where it might be necessary, and that is for `@deprecated` because we cannot decorate an attribute.
> > 
> > 
> > Hm, I could live with the current approach, something like `field(..., deprecated=...)`.
> 
> I am thinking of something slightly different. For `field` deprecation I think that's the only way we can do it currently until decorators can be attached to attributes and annotations, which I don't really know how that would work. What I was thinking of deprecating via stub files is if a plugin has:
> 
> ```
> from tmt.utils import field
> ```
> 
> which would deprecate to point the developer to `tmt.dataclasses.field` instead. For most cases we can create a shim, but if we want to deprecate a constant/variable, that is significantly more challenging. We can do it with the stub files though because we can simply lie about its type in there.

I'm not sure we speak about the same kind of deprecation. I meant one when a "metadata key" or CLI option gets deprecated from users' PoV. Like `--format`:

```python
@option(
    '--format', default=_test_export_default, 
    show_default=True,
    help='Output format.',
    deprecated=Deprecated('1.21', hint='use --how instead'),
    choices=_test_export_formats)
```

I'm starting tot think you meant deprecating use of `dataclass.field` itself. Is that correct?

> > > * unify the `fmf` spec documentation with the python code (or if we are bold we could even generate/append the python docstring from the fmf files, but not sure if IDEs would render it)
> > 
> > 
> > WDYT about code being the source here? My idea was to make plugin code the single source of truth, and generate plugin documentation, schema, and everything from the code of the plugin. The same would apply to spec like test/plan/story fields.
> 
> 👍 to that. Would work similar with the json schema generation.
> 
> > > * generate json schema from the annotations
> > 
> > 
> > Yep, that's one of the goals :)
> 
> [Here](https://github.com/scikit-build/scikit-build-core/blob/main/src/scikit_build_core/settings/skbuild_schema.py) is some reference form `scikit-build-core`. I think we can simplify it a lot with jinja templating.

Yep, I played a bit with Jinja and plugins while creating plugin docs, I got some general feeling, and this should be definitely doable. I would very much like to add some library that would let us reliably process annotations, manually it's a PITA to distinguish between `int` and `list[int]` with all corner cases. And I think such a library would be needed for this endeavor where we want to convert dataclass field into a JSON schema describing it... Maybe there's a piece in `attrs` we could use for this.

> > > * generally most other features could be handled by inheritance and `__init_subclass__`, but maybe some parts are easier done by overriding the `dataclass` instead, annotations stuff being one of them that I know of
> > > 
> > > But another main reason is for plugin developers to guarantee that any improvements made on the base tmt containers do not require any refactoring on their side.
> > 
> > 
> > I think we are aligned, at least in general, and what remains are the technicalities. For example, this move of "base container classes" into other own location, absolutely. What I'm less sure is whether we speak the same language when it comes to names, e.g.
> > > Any thoughts on renaming dataclass to something distinct from vanilla dataclass/attrs.define? What about tmt_data/fmf_data, and maybe similarly tmt_field/fmf_field?
> > 
> > 
> > If you mean the original `dataclasses.dataclass` decorator, and you think we should use it in tmt code instead of "raw" `@dataclasses.dataclass`, then yes, I think that makes sense - for me, the benefit would be we could change the implementation of `tmt.container.whateverdecorator` without polluting diff with oneliners changing what decorator is used in all plugins and base. So this makes sense from this PoV.
> 
> Indeed we are in sync on this thought 👍.
> 
> > Just a couple of notes:
> > ```
> > * I would really like to avoid "data". I don't like "step data", I think "data" as a term is very vague, it can mean anything, depending on context, it's hard to speak about without ambiguity, and so on. I liked "container" because it seems less "data"-ish than `dataclass` and still represents what the class is used for, a container for, well, data. Fields. That's why I added various `container_*` helpers, so I for one would do something like `from dataclasses import dataclass as container`.
> > ```
> 
> Hmm, makes sense. One alternative is `attrs` syntax of `define`, wdyt? I like the looks of `tmt.containers.define` much better than `dataclass`'s snytax.

`@container` doesn't look bad either :) `@define` looks like a repetition to me - I am already defining a class, I know that, that's why I wrote `class Foo`, why do I need to `@define` it even more? On the other hand, `@dataclass` or `@container` seems like marking a class with its purpose, which makes more sense to me.

> > ```
> > * I like "field", it seems to be an acceptable term to both dataclasses and attrs, and it fits the namespace in my head. We have our custom implementation, once everything does `from tmt.containers import field`, do we even need to call it `tmt_field`/`fmf_field`? I'm not sure I understand the need for a distinct name here.
> > ```
> 
> This can be relaxed. It's mostly from navigating the `tmt` code and finding `field()` and it is not clear if it's `dataclasses.field` or `tmt.utils.field`. That of course can be fixed with `ruff` to request qualified names, and maybe we can ship some recommended `ruff` settings for plugin developing.

I suppose `tmt.utils.field` exists because `dataclasses.field` exists, and there is still a bit of a mess in terminology and what names are used for variables - field, key, option, sometimes field-ish name holds CLI option and so on. If we forbid `dataclass.field`, it should become clearer.

> > ```
> > * I'm not 100% sure we would be able to perform the transition as painlessly as I mentioned above, i.e. without polluting plugins with trivial import changes; given how entangled everything is internal, getting things perfect enough that we would just swap one implementation for another without plugins noticing is a very tall order - we may end up with some `field_new` or field_v2` temporarily, and I for one would be fine with that, as long as there is a good reason and a plan how to resolve it, in the next release, for example. We have some breathing space, although it would be fine to not regress in functionality too much, too often and for too long :)
> > ```
> 
> You mean w.r.t. review or with functionality? And I guess this is for the `tmt` code only, or maybe there are some other `tmt` plugins that I should keep in mind to preserve compatibility. If it's the former, then shouldn't it be resolved by splitting the PR into more minimal commits?

Both review and functionality. Smaller steps are easier to review, as long as there's some documented transition path that's being followed.

There are definitely out-of-tree plugins we need to care about, luckily we do run several tests on every tmt PR checking these as well, so we should get notified as soon as we break something. And often it may end up with fix of those plugins, again, if it's understood why and for how long a apparently weird change is needed, it's easier to sell and handle.

> > ```
> > * I'd very much argue in favor of multiple PRs. While it's possible to put multiple nice commits into one PR, when the merge time comes, it's harder to squash what should be squashed, and preserve history. Also the review seems to work better when it's less changes in one PR, at least when a potential reviewer checks the PR for the first time - seeing 50 changed [...]

2024-09-25 19:57 UTC, happz commented
Adding this one to 1.38, let's see whether it can be done as a whole.

2024-10-09 17:34 UTC, LecrisUT commented
Attempt2. This time I've separated the usage into `tmt.container` and vanilla `dataclaess.dataclass`. One that is rather ambiguous is `tmt.queue.Task`, wondering if that should also be covered, maybe by a different `container`-like? Anyway, this one might be a bit easier to review when split into these 2 commits.

- Currently `mypy` is mad at me because `container = dataclasses.dataclass` doesn't seem to be recognized well
- I have only copied the implementation from `tmt.utils`, but I think `tmt.container` should be further split into smaller files
- What happened in `tmt.steps.prepare:Prepare.go().DependencyCollection`, why is that dataclass definition inside a function?

2024-10-11 05:53 UTC, happz commented
> Attempt2. This time I've separated the usage into `tmt.container` and vanilla `dataclaess.dataclass`. One that is rather ambiguous is `tmt.queue.Task`, wondering if that should also be covered, maybe by a different `container`-like? Anyway, this one might be a bit easier to review when split into these 2 commits.

I'll definitely check it out before I'm done today. It looks like a good candidate for 1.38.

> * Currently `mypy` is mad at me because `container = dataclasses.dataclass` doesn't seem to be recognized well

I think mypy even has some special handling for `dataclasses`, the assignment might break it, yada yada, we'll end up with a hopefully temporary `# type: ignore`...

> * I have only copied the implementation from `tmt.utils`, but I think `tmt.container` should be further split into smaller files

Could be, although I for one would be happy by the move alone, more granularity might make things harder to follow again. It's an extreme example now, I'd like to avoid swinging to the opposite side of granularity scale :) But let's see.

> * What happened in `tmt.steps.prepare:Prepare.go().DependencyCollection`, why is that dataclass definition inside a function?

Nothing serious, it's a class that's used only in that method, so I made it a nested one. It can be there, it doesn't have to be there, it's up to us. It's probably the only one in tmt codebase, I suppose it could be argued that it should move out of the method.

2024-11-26 10:02 UTC, psss commented
Already marked as a `must-have`, proposed for now for `1.40`. Let's try to rebase on the latest `main` and finish until next Friday, if possible.

2025-01-14 10:29 UTC, thrix commented
@happz please find out what to do with this if we can make it in the release

2025-01-23 16:17 UTC, happz commented
> @happz please find out what to do with this if we can make it in the release

Most likely not, despite the `priority | must`. I'm working on the rebase now - yeah, I could ping @LecrisUT, and he would do it, but I felt it's been delayed so many times I should invest some work into the progress myself. Unfortunately, pre-commit reports many type-related issues that need to be sorted out, I'll try to work on them tomorrow, but I'm afraid it won't be a one-liner fix. But I would like to get it merged, perhaps first thing in 1.43 so it gets a nice review and more testing during the 1.43 development window?

2025-01-24 08:36 UTC, psss commented
> But I would like to get it merged, perhaps first thing in 1.43 so it gets a nice review and more testing during the 1.43 development window?

That sounds reasonable to me.

2025-01-27 19:27 UTC, thrix commented
> > But I would like to get it merged, perhaps first thing in 1.43 so it gets a nice review and more testing during the 1.43 development window?
> 
> That sounds reasonable to me.

moved to 1.43

2025-01-30 11:40 UTC, happz commented on tmt/base.py
> +@dataclasses.dataclass(repr=False)  # noqa: TID251
This could be `@container`.

2025-01-30 11:40 UTC, happz commented on tmt/base.py
> +@dataclasses.dataclass  # noqa: TID251
This could be `@container`.

2025-01-30 11:40 UTC, happz commented on tmt/checks/watchdog.py
> +@dataclasses.dataclass  # noqa: TID251
This could be `@container`.

2025-01-30 11:41 UTC, happz commented on tmt/cli/__init__.py
> +@dataclasses.dataclass  # noqa: TID251
This could be `@container`.

2025-01-30 11:41 UTC, happz commented on tmt/cli/__init__.py
> +@dataclasses.dataclass  # noqa: TID251
This could be `@container`.

2025-01-30 11:41 UTC, happz commented on tmt/hardware.py
> +@dataclasses.dataclass  # noqa: TID251
This could be `@container`.

2025-01-30 12:29 UTC, LecrisUT commented on tmt/cli/__init__.py
> +@dataclasses.dataclass  # noqa: TID251
The reason why I didn't convert those is to make it easier to extend the container types, e.g. for parsing docstrings. The cases where I didn't convert is because they do not seem to have a link to the `.fmf` entries.

2025-01-30 13:18 UTC, LecrisUT commented
I think for now to get the first part of splitting the `container` logic to its own package, should be ok. We can workshop the requirements more in the attrs PR.

2025-02-06 12:18 UTC, happz commented
/packit build

2025-02-07 10:42 UTC, happz commented
/packit build

2025-02-07 11:07 UTC, psss requested changes
Looks good. It just seems that some of the docstring changes were lost during the merge from `main`. I guess it would be good to do a rebase instead?

2025-02-07 12:41 UTC, psss approved these changes

2025-02-07 12:42 UTC, psss commented
/packit build

2025-02-10 09:06 UTC, psss commented
/packit test

2025-02-10 10:06 UTC, lukaszachy approved these changes

2025-02-10 10:14 UTC, therazix approved these changes

2025-02-10 10:46 UTC, martinhoyer approved these changes
LGTM at glance. Just minor nitpicks/questions.  

Are we sure about the name `container`? I don't have a better one myself, just raising it as I imagine it could clash with lxc nomenclature.

2025-02-10 10:46 UTC, martinhoyer commented on pyproject.toml
> +"dataclasses.field".msg = "Are you sure you don't want tmt.container.field instead."
Perhaps the messages should say something in a sense of "use tmt.container.foo or add noqa if you are sure"?

2025-02-10 10:46 UTC, martinhoyer commented on tmt/cli/__init__.py
> +    steps: set[str] = dataclasses.field(default_factory=set)  # noqa: TID251
Maybe just a short explanation for the noqas'?  I mean, it's obvious now, but would be helpful for future readers. I think we have a convention to comment all ignore checks right? Don't see it in contribute doc though.

2025-02-10 11:56 UTC, LecrisUT commented on tmt/cli/__init__.py
> +    steps: set[str] = dataclasses.field(default_factory=set)  # noqa: TID251
Probably we could go with some renaming, `property`/`attribute`/`member` etc. Probably we can tackle that when we see how we can tweak the containers, because we might not need to do it if the only metadata is `help` (that could be taken from the docstring).

2025-02-10 11:57 UTC, happz commented on tmt/cli/__init__.py
> +    steps: set[str] = dataclasses.field(default_factory=set)  # noqa: TID251
Ok, added `dataclass.field` as `tmt.container.simple_field`. It's not perfect, and there will be patches renaming `field` and `simple_field` and so on, but I can't figure a simpler way. At least we avoid `dataclass.field()` in the tmt code completely.

2025-02-10 11:57 UTC, happz commented on pyproject.toml
> +"dataclasses.field".msg = "Are you sure you don't want tmt.container.field instead."
Rewritten in [cd154f3](https://github.com/teemtee/tmt/pull/3195/commits/cd154f37084a4183a36752568a862993f645b5f0)

2025-02-10 12:00 UTC, LecrisUT commented
> Are we sure about the name `container`? I don't have a better one myself, just raising it as I imagine it could clash with lxc nomenclature.

Better naming for sure would be good. Right now there is the tree nomenclature for everything that has to do with the `fmf` path, but we would need something for the yaml contents on each branch/leaf.

2025-02-10 12:05 UTC, happz commented
/packit build

2025-02-10 13:14 UTC, psss commented on tmt/cli/__init__.py
> +    steps: set[str] = dataclasses.field(default_factory=set)  # noqa: TID251
Nicely done! :+1:

2025-02-10 13:26 UTC, psss commented
> > Are we sure about the name `container`? I don't have a better one myself, just raising it as I imagine it could clash with lxc nomenclature.
> 
> Better naming for sure would be good. Right now there is the tree nomenclature for everything that has to do with the `fmf` path, but we would need something for the yaml contents on each branch/leaf.

So the base class is `DataContainer`, we could use `datacontainer` instead of `container` but I'd say these double-word names do not look very nice. I'd suggest to keep `container` for now, not a big deal, we can rename later if a better idea comes.

2025-02-10 13:31 UTC, happz commented
> > > Are we sure about the name `container`? I don't have a better one myself, just raising it as I imagine it could clash with lxc nomenclature.
> > 
> > 
> > Better naming for sure would be good. Right now there is the tree nomenclature for everything that has to do with the `fmf` path, but we would need something for the yaml contents on each branch/leaf.
> 
> So the base class is `DataContainer`, we could use `datacontainer` instead of `container` but I'd say these double-word names do not look very nice. I'd suggest to keep `container` for now, not a big deal, we can rename later if a better idea comes.

FTR, `DataContainer` may disappear. It was my addition to having a unified base for classes that serve as containers for data, to replace dictionaries, and provide some shared functionality - converting to dictionaries, iterating over fields, and so on. And we may get that "for free" with some clever usage and setup of `attrs` or `Pydantic`. We'll see.

2025-02-10 14:28 UTC, merged

2025-02-28 08:10 UTC, lukaszachy commented
Added label as this broke out-of-the tree tmt plugin