Our regular monthly move of ssh master sockets
teemtee/tmt pull request #3196
Opened 2024-09-05 20:51 UTC by happz

Pull Request Checklist

* [x] implement the feature
* [ ] extend the test coverage

2024-09-05 21:05 UTC, happz commented
/packit test

2024-09-06 08:51 UTC, martinhoyer approved these changes
Well if there is a ssh problem with ssh-socket path again with this, there really is something cursed.

2024-09-06 10:03 UTC, seberm approved these changes
If this is going to be a bugfix release `tmt-1.36.1`, you should probably describe the changes in the release notes (`releases.rst`).

2024-09-06 17:59 UTC, happz commented
> If this is going to be a bugfix release `tmt-1.36.1`, you should probably describe the changes in the release notes (`releases.rst`).

Hmm, I think it does deserve a release note, but for 1.37 - I would expect release notes for 1.36.1 to be constructed in commit(s) creating 1.36.1 out of `1.36.0` tag, I suppose some cherry-picking of needed bugfixes + a commit with release stuff.

2024-09-10 11:41 UTC, therazix approved these changes

2024-09-10 11:43 UTC, KwisatzHaderach approved these changes

2024-09-10 13:33 UTC, psss requested changes
Changes look good, just noticed one test nitpick. However, I'm not sure that the master ssh connection actuallly works. Tested with a simple `tmt init -t mini && tmt run` and it seems that it takes about one second to execute each ssh command:

    15:14:38   Run command: ssh ... -S/var/tmp/tmt/run-017/ssh-sockets/127.0.0.1-10022-root.socket ... cat /etc/os-release'
    15:14:39   Run command: ssh ... -S/var/tmp/tmt/run-017/ssh-sockets/127.0.0.1-10022-root.socket ... cat /etc/lsb-release'
    15:14:39   Run command: ssh ... -S/var/tmp/tmt/run-017/ssh-sockets/127.0.0.1-10022-root.socket ... arch'
    15:14:40   Run command: ssh ... -S/var/tmp/tmt/run-017/ssh-sockets/127.0.0.1-10022-root.socket ... uname -r'
    15:14:42   Run command: ssh ... -S/var/tmp/tmt/run-017/ssh-sockets/127.0.0.1-10022-root.socket ... apk --version'
    15:14:43   Run command: ssh ... -S/var/tmp/tmt/run-017/ssh-sockets/127.0.0.1-10022-root.socket ... apt --version'
    15:14:44   Run command: ssh ... -S/var/tmp/tmt/run-017/ssh-sockets/127.0.0.1-10022-root.socket ... /bin/bash -c '"'"'
    15:14:45   Run command: ssh ... -S/var/tmp/tmt/run-017/ssh-sockets/127.0.0.1-10022-root.socket ... dnf5 --version'
    15:14:46   Run command: ssh ... -S/var/tmp/tmt/run-017/ssh-sockets/127.0.0.1-10022-root.socket ... /bin/bash -c '"'"'
    15:14:47   Run command: ssh ... -S/var/tmp/tmt/run-017/ssh-sockets/127.0.0.1-10022-root.socket ... stat /run/ostree-booted'
    15:14:48   Run command: ssh ... -S/var/tmp/tmt/run-017/ssh-sockets/127.0.0.1-10022-root.socket ... cat /proc/filesystems'

Shouldn't these simple commands run much faster? What would be an easy check to ensure that the master connection was actually used? Anyway, I have a feeling that the problem is there for some time already (not caused by this patch). But I'd say it would be good to get it fixed anyway.

2024-09-10 15:24 UTC, psss commented
So the problem was caused by trying to spawn the master ssh connection before the guest was ready. We need to check that guest is up before creating the master socket. To be addressed in a separate pull request.

2024-09-11 08:24 UTC, psss commented on tests/provision/ssh-multiplexing/test.sh
> +        # rlRun "rm -r $long_run" 0 "Remove run directory with the long name"
Or is it commented intentionally?

2024-09-11 08:36 UTC, happz commented on tests/provision/ssh-multiplexing/test.sh
> +        # rlRun "rm -r $long_run" 0 "Remove run directory with the long name"
Nope, fixed in c4dcb385.

2024-09-12 07:02 UTC, happz commented
/packit test

2024-09-12 07:25 UTC, happz commented
/packit test

2024-09-12 08:25 UTC, happz commented
/packit test

2024-09-12 10:25 UTC, psss commented
Failing test is an irrelevant `dhclient` avc error, everythin else green, merging.

2024-09-12 10:27 UTC, merged