Readme badges and pyproject cleanup
teemtee/tmt pull request #3378
Opened 2024-11-25 13:05 UTC by martinhoyer

I'm not a friend with rst and have more experience with markdown. Will this render ok on PyPI page and other places? We also need to deal with man generation I presume?
PyPA should be ok based on: 
```
$ twine check dist/tmt-1.40.0.dev2+ga31e8651-py3-none-any.whl --strict
Checking dist/tmt-1.40.0.dev2+ga31e8651-py3-none-any.whl: PASSED
```

github would look like this:
![image](https://github.com/user-attachments/assets/2a4b3aed-8835-48be-8a41-e48dd7e07293)

In pyproject, I've replaced Python 3.11 with 3.13 and removed the unmaintainable comments of what versions are available where.

Pull Request Checklist

* [x] implement the feature

2025-04-10 13:41 UTC, martinhoyer commented
![image](https://github.com/user-attachments/assets/fdf9cf56-0dfb-490b-9dd7-6bb32f4e72b1)

Needs consensus on what badges are actually useful (which once to pick) and which of those make sense for them to be dynamic (versions, build successful).

I would say that Copr can be renamed to "Development/nighly builds" and just point to teemtee/latest, for example.

2025-04-10 13:48 UTC, happz commented
> ![image](https://private-user-images.githubusercontent.com/20230297/432315399-fdf9cf56-0dfb-490b-9dd7-6bb32f4e72b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQyOTI5MDgsIm5iZiI6MTc0NDI5MjYwOCwicGF0aCI6Ii8yMDIzMDI5Ny80MzIzMTUzOTktZmRmOWNmNTYtMGRmYi00OTBiLTlkZDctNmJiMzJmNGU3MmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDEwVDEzNDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZTQ4MjM0NmM2ODJlMGZiNDgwOTY3MzBjZGUzYTRlY2M5NDc0MDJhYzgxNjdiYjA3YjZjZDFiNDdiODY0NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4r5SVOA-fKz-bCimrr0qmuLvnP1T9z4xaZ3FBVQGTWI)
> 
> Needs consensus on what badges are actually useful (which once to pick) and which of those make sense for them to be dynamic (versions, build successful).
> 
> I would say that Copr can be renamed to "Development/nighly builds" and just point to teemtee/latest, for example.

I'd probably drop "ruff" and "pre-commit", the rest will lead a user to some artifacts or docs, while these two are more like a statement, "yup, we test it", and we don't expect these to ever be red for `main` branch, correct?

2025-04-16 13:15 UTC, psss commented
> I'd probably drop "ruff" and "pre-commit", the rest will lead a user to some artifacts or docs, while these two are more like a statement, "yup, we test it", and we don't expect these to ever be red for `main` branch, correct?

Agreed, I feel it the same way.

2025-04-16 13:16 UTC, psss requested changes
Let's use the fresh copr link.

2025-04-17 11:00 UTC, thrix requested changes

2025-04-23 14:05 UTC, martinhoyer commented on pyproject.toml
> -    "urllib3>=1.26.5, <3.0",  # 1.26.16 / 2.0.4
@thrix Well, it seems unmaintainable, definitely was a mistake to add Fedora versions there. Mea culpa.  

I presume we can add "explanation" for the lock, like "version xyz available on epel9 [04/2015]" or something", but not sure if there is any value as that is the case for all of them: "Min versions are dictated by minimal versions of RHEL/EPEL9 because we don't have something like https://github.com/teemtee/tmt/pull/3605, this is also why we have Python 3.9, even though it will be EOL in 6 months"

2025-04-23 16:55 UTC, martinhoyer commented
> I'd probably drop "ruff" and "pre-commit", the rest will lead a user to some artifacts or docs, while these two are more like a statement, "yup, we test it", and we don't expect these to ever be red for `main` branch, correct?

> Agreed, I feel it the same way.

@psss @happz I don't see what's wrong with that. It just tells people that this project uses pre-commit and ruff, which can increase the respect for the project, making them more likely to get involved. I mean, it's literally called a "badge".  

Alas, removed as requested.

2025-04-29 11:31 UTC, mcasquer commented on README.rst
> +|docs| |matrix| |fedora-pkg| |copr-build| |pypi-version| |python-versions| |ruff| |pre-commit| |license|
```suggestion
|docs| |matrix| |fedora-pkg| |copr-build| |pypi-version| |python-versions| |license|
```
@martinhoyer these should be removed from here as well

2025-04-29 14:38 UTC, martinhoyer commented on README.rst
> +|docs| |matrix| |fedora-pkg| |copr-build| |pypi-version| |python-versions| |ruff| |pre-commit| |license|
haha, nice one martin.

2025-04-30 06:40 UTC, mcasquer commented
@martinhoyer LGTM, just a thought: do you think we can point the `python-versions` badge to a different place than pypi? IMHO some place in the docs would be better although I haven't found anything apart from a [brief mention in the Unit Tests](https://tmt.readthedocs.io/en/stable/contribute.html#unit-tests) section

2025-04-30 14:45 UTC, happz commented
Seems to be rendering well in both HTML docs and man page: neither of these two shows any sign of badges :/ Which I guess is fine, yet a bit surprising.

2025-05-01 13:59 UTC, happz commented on pyproject.toml
> +    "Programming Language :: Python :: 3.12",
I understand the explanation of switching to 3.13 in `tool.hatch.envs.test.matrix` below, but why dropping 3.11 "badge of compatibility" completely? tmt should be still quite usable with Python 3.11, and Python 3.11 EOL is in 2027 or something. Adding 3.12 and 3.13, sure, removing 3.11 does not seem right.

2025-05-05 21:25 UTC, martinhoyer commented on pyproject.toml
> +    "Programming Language :: Python :: 3.12",
Sure, but then we probably want to add all 9-13?

2025-05-05 21:32 UTC, martinhoyer commented on README.rst
> +    :target: https://copr.fedorainfracloud.org/coprs/g/teemtee/stable/
Do we really want `/stable/`? I would say `/latest/` make more sense...

2025-05-05 21:37 UTC, martinhoyer commented on pyproject.toml
> +    "Programming Language :: Python :: 3.12",
added

2025-05-06 07:15 UTC, happz commented on pyproject.toml
> +    "Programming Language :: Python :: 3.12",
I agree, 3.10 should be there too. No idea why it's missing.

2025-05-06 14:51 UTC, thrix commented on README.rst
> +    :target: https://copr.fedorainfracloud.org/coprs/g/teemtee/stable/
@martinhoyer can you update it pls?

2025-05-07 07:16 UTC, mcasquer approved these changes
LGTM

2025-05-15 07:13 UTC, happz commented on .pre-commit-config.yaml
> +          - "urllib3>=1.26.5, <2.0"
Indeed. @martinhoyer please, check this out, and the rest of requirements if possible too, just it case there another typo like this one.

2025-05-15 10:11 UTC, martinhoyer commented on .pre-commit-config.yaml
> +          - "urllib3>=1.26.5, <2.0"
no this is correct. there is urllib 1x on EL10 and urllib 2x on Fedora

2025-05-19 12:53 UTC, martinhoyer commented on .pre-commit-config.yaml
> +          - "urllib3>=1.26.5, <2.0"
oh! I'm blind. Thanks. Too bad graphite added extra `+` symbol btw

2025-05-19 13:17 UTC, happz approved these changes

2025-05-19 13:20 UTC, happz commented on .pre-commit-config.yaml
> +          - "urllib3>=1.26.5, <2.0"
Yeah, correct... 

@martinhoyer ^^

2025-05-19 15:07 UTC, happz commented on pyproject.toml
> +    "mrack>=1.23.3",
```suggestion
    "mrack>=1.23.2",
```

This is not going to work, according to PyPI, the most recent version is     `1.23.2`.

2025-05-20 07:10 UTC, merged