Always enable pseudo-terminal for ssh connections
teemtee/tmt pull request #999
Opened 2022-01-13 14:46 UTC by psss

Some tests require pseudo-terminal to work correctly.

Resolves #998.

2022-01-14 08:28 UTC, lukaszachy commented
OK, but we should find a place where to document this as some test might want the opposite (and it is different from what beaker/restraint does by default).
Also this should be common feature across all provision methods.

2022-01-17 18:19 UTC, thrix commented
yeah, exactly ... and I believe it should be configurable per test ... in restraint metadata I see `use_pty` option ....

2022-01-25 14:30 UTC, lukaszachy commented
We don't run VM tests in the CI? 
I've tried locally and it failed on prepare (push part)
```
    prepare
        fail: Failed to push workdir to the guest. This usually means login as 'root' to the test machine does not work.
stderr (4/4 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Warning: Permanently added '[127.0.0.1]:10051' (ED25519) to the list of known hosts.
protocol version mismatch -- is your shell clean?
(see the rsync man page for an explanation)
rsync error: protocol incompatibility (code 2) at compat.c(600) [sender=3.2.3]

Failed to run command 'rsync -Rrz --links --safe-links --delete -e ssh -tt -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oIdentitiesOnly=yes -p 10051 -i /var/tmp/tmt/run-072/plans/default/provision/default/id_ecdsa -S /run/user/17062/tmt/tmpy8mn41vq /var/tmp/tmt/run-072/plans/default root@127.0.0.1:/'. Reason: Command returned '2'.

```

2022-01-25 14:35 UTC, lukaszachy requested changes
-tt broke rsync (fedora35, `tmt run` command)

2022-08-30 09:04 UTC, lukaszachy commented
FTR: #1387 might need to add -t/tt to make signals work. We still need Test metadata to let test request tty.

2023-06-13 11:12 UTC, psss commented
So, I guess, always enabling pseudo-termial is not the answer. Closing

2023-06-13 11:12 UTC, closed without merging